// Context-aware help for each CLI mode

export const helpData = {
  user: {
    'enable': 'Turn on privileged commands',
    'exit': 'Exit from the EXEC',
    'logout': 'Exit from the EXEC',
    'ping': 'Send echo messages',
    'show': 'Show running system information',
    'traceroute': 'Trace route to destination',
    'terminal': 'Set terminal line parameters',
  },
  privileged: {
    'clear': 'Reset functions',
    'clock': 'Manage the system clock',
    'configure': 'Enter configuration mode',
    'copy': 'Copy from one file to another',
    'debug': 'Debugging functions',
    'delete': 'Delete a file',
    'dir': 'List files on filesystem',
    'disable': 'Turn off privileged commands',
    'enable': 'Turn on privileged commands',
    'erase': 'Erase a filesystem',
    'exit': 'Exit from the EXEC',
    'logout': 'Exit from the EXEC',
    'more': 'Display file contents',
    'no': 'Negate a command or set its defaults',
    'ping': 'Send echo messages',
    'reload': 'Halt and perform a cold restart',
    'rename': 'Rename a file',
    'setup': 'Run the setup wizard',
    'show': 'Show running system information',
    'ssh': 'Open SSH connection',
    'telnet': 'Open Telnet connection',
    'terminal': 'Set terminal line parameters',
    'traceroute': 'Trace route to destination',
    'undebug': 'Disable debugging functions',
    'verify': 'Verify a file',
    'vlan': 'VLAN commands',
    'write': 'Write running configuration to memory',
  },
  globalConfig: {
    'aaa': 'Authentication, Authorization, Accounting',
    'access-list': 'Add an access list entry',
    'banner': 'Define a login banner',
    'cdp': 'Global CDP configuration subcommands',
    'clock': 'Configure time-of-day clock',
    'crypto': 'Encryption module',
    'do': 'To run exec commands in config mode',
    'enable': 'Modify enable password parameters',
    'end': 'Exit from configure mode',
    'errdisable': 'Error disable configuration',
    'exit': 'Exit from configure mode',
    'hostname': 'Set system\'s network name',
    'interface': 'Select an interface to configure',
    'ip': 'Global IP configuration subcommands',
    'lldp': 'Global LLDP configuration',
    'line': 'Configure a terminal line',
    'logging': 'Modify message logging facilities',
    'no': 'Negate a command or set its defaults',
    'ntp': 'Configure NTP',
    'service': 'Modify use of network based services',
    'snmp-server': 'Modify SNMP parameters',
    'spanning-tree': 'Spanning Tree Subsystem',
    'udld': 'Global UDLD configuration',
    'username': 'Establish User Name Authentication',
    'vlan': 'VLAN commands',
    'vtp': 'Configure VTP',
  },
  interfaceConfig: {
    'carrier-delay': 'Specify delay for interface transitions',
    'cdp': 'CDP interface subcommands',
    'channel-group': 'Assign an Ethernet interface to an EtherChannel group',
    'channel-protocol': 'Select the channel protocol (LACP or PAgP)',
    'description': 'Interface specific description',
    'do': 'To run exec commands in config mode',
    'duplex': 'Configure duplex operation',
    'end': 'Exit from configure mode',
    'exit': 'Exit from interface configuration mode',
    'flowcontrol': 'Set flow control for an interface',
    'ip': 'Interface Internet Protocol config commands',
    'keepalive': 'Enable keepalive',
    'mtu': 'Set the interface Maximum Transmission Unit (MTU)',
    'no': 'Negate a command or set its defaults',
    'shutdown': 'Shutdown the selected interface',
    'spanning-tree': 'Spanning Tree Subsystem',
    'speed': 'Configure speed operation',
    'storm-control': 'Storm Control',
    'switchport': 'Set switching mode characteristics',
  },
  vlanConfig: {
    'end': 'Exit from configure mode',
    'exit': 'Exit from VLAN configuration mode',
    'mtu': 'VLAN Maximum Transmission Unit',
    'name': 'Ascii name of the VLAN',
    'no': 'Negate a command or set its defaults',
    'state': 'Operational state of the VLAN',
  },
  lineConfig: {
    'do': 'To run exec commands in config mode',
    'end': 'Exit from configure mode',
    'exec-timeout': 'Set the EXEC timeout',
    'exit': 'Exit from line configuration mode',
    'flowcontrol': 'Set flow control',
    'history': 'Enable and control the command history function',
    'length': 'Set number of lines on a screen',
    'logging': 'Modify message logging facilities',
    'login': 'Enable password checking',
    'no': 'Negate a command or set its defaults',
    'password': 'Set a password',
    'privilege': 'Change privilege level for line',
    'session-timeout': 'Set interval for closing connection',
    'speed': 'Set the transmit and receive speeds',
    'stopbits': 'Set async line stop bits',
    'transport': 'Define transport protocols for line',
    'width': 'Set width of the display terminal',
  },
};

export const showHelp = {
  'arp': 'ARP table',
  'boot': 'Boot variables',
  'cdp': 'CDP information',
  'clock': 'Display the system clock',
  'controllers': 'Interface controller status',
  'environment': 'Environmental status',
  'errdisable': 'Error disabled mechanism',
  'etherchannel': 'EtherChannel information',
  'flash': 'Flash filesystem information',
  'history': 'Display the session command history',
  'interfaces': 'Interface status and configuration',
  'inventory': 'Hardware inventory',
  'ip': 'IP information',
  'lldp': 'LLDP information',
  'log': 'Display syslog buffer',
  'mac-address-table': 'MAC forwarding table',
  'module': 'Module information',
  'platform': 'Platform information',
  'power': 'Power information',
  'privilege': 'Show current privilege level',
  'processes': 'Active process statistics',
  'running-config': 'Current operating configuration',
  'sessions': 'Open sessions',
  'spanning-tree': 'Spanning tree topology',
  'startup-config': 'Contents of startup configuration',
  'terminal': 'Terminal settings',
  'udld': 'UDLD information',
  'users': 'Display users on the system',
  'version': 'System hardware and software status',
  'vlan': 'VTP VLAN status',
  'vtp': 'VTP information',
};

export function getHelpForMode(mode) {
  switch (mode) {
    case 'user': return helpData.user;
    case 'privileged': return helpData.privileged;
    case 'globalConfig': return helpData.globalConfig;
    case 'interfaceConfig': return helpData.interfaceConfig;
    case 'vlanConfig': return helpData.vlanConfig;
    case 'lineConfig': return helpData.lineConfig;
    default: return helpData.user;
  }
}

export function getCompletions(partial, mode) {
  const commands = getHelpForMode(mode);
  const lower = partial.toLowerCase();
  return Object.keys(commands).filter(cmd => cmd.startsWith(lower));
}