import { createDefaultSwitchState } from './switchState';

// Helper to create a broken switch state for troubleshooting labs
function brokenState(overrides) {
  const base = createDefaultSwitchState();
  return { ...base, ...overrides };
}

export const scenarios = [
  {
    id: 'basic-navigation',
    title: 'CLI Navigation Basics',
    difficulty: 'Beginner',
    duration: '10 min',
    description: 'Learn to navigate between CLI modes: User EXEC, Privileged EXEC, and Global Configuration mode.',
    objectives: [
      'Enter Privileged EXEC mode using "enable"',
      'Enter Global Configuration mode using "configure terminal"',
      'Change the hostname to "MySwitch"',
      'Return to Privileged EXEC mode using "end"',
      'View the running configuration',
    ],
    hints: [
      'Start by typing "enable" to enter Privileged EXEC mode',
      'Use "configure terminal" or "conf t" to enter config mode',
      'Use "hostname MySwitch" to change the name',
      'Type "end" to return to Privileged EXEC',
      'Use "show running-config" to verify your changes',
    ],
    commands: [
      { cmd: 'enable', why: 'Moves from User EXEC (Switch>) to Privileged EXEC (Switch#). You must do this before entering configuration mode.' },
      { cmd: 'configure terminal', why: 'Enters Global Configuration mode (Switch(config)#). All device-wide settings are made from here.' },
      { cmd: 'hostname MySwitch', why: 'Changes the switch display name. The prompt immediately updates to MySwitch(config)#.' },
      { cmd: 'end', why: 'Jumps directly back to Privileged EXEC from any config mode. Equivalent to pressing Ctrl+Z on a real switch.' },
      { cmd: 'show running-config', why: 'Displays the active configuration in RAM. Verify the hostname line now reads "hostname MySwitch".' },
    ],
    validation: (state) => {
      return [
        { label: 'Enter Privileged EXEC mode using "enable"', pass: !!state.visitedPrivileged },
        { label: 'Enter Global Configuration mode using "configure terminal"', pass: !!state.visitedGlobalConfig },
        { label: 'Change the hostname to "MySwitch"', pass: state.hostname?.toLowerCase() === 'myswitch' },
        { label: 'Return to Privileged EXEC mode using "end"', pass: !!state.returnedToPrivileged },
        { label: 'View the running configuration', pass: !!state.viewedRunningConfig },
      ];
    },
    initialState: null,
  },
  {
    id: 'vlan-config',
    title: 'VLAN Configuration',
    difficulty: 'Intermediate',
    duration: '15 min',
    description: 'Create VLANs and assign ports to different VLANs for network segmentation.',
    objectives: [
      'Create VLAN 10 and name it "SALES"',
      'Create VLAN 20 and name it "ENGINEERING"',
      'Assign FastEthernet0/1 through Fa0/6 to VLAN 10',
      'Assign FastEthernet0/7 through Fa0/12 to VLAN 20',
      'Verify with "show vlan brief"',
    ],
    hints: [
      'Enter config mode, then use "vlan 10" to create a VLAN',
      'Use "name SALES" inside VLAN config mode, then "exit" back to global config',
      'Use "interface fa0/1" then "switchport mode access" then "switchport access vlan 10"',
      'Repeat for each port you want to assign',
      'Use "show vlan brief" to verify assignments',
    ],
    commands: [
      { cmd: 'enable', why: 'Enter Privileged EXEC mode before making changes.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
      { cmd: 'vlan 10', why: 'Creates VLAN 10 and enters VLAN config mode. VLANs segment a switch into isolated broadcast domains.' },
      { cmd: 'name SALES', why: 'Assigns a human-readable name to VLAN 10 so it is identifiable in show commands.' },
      { cmd: 'exit', why: 'Returns from VLAN config mode back to Global Configuration mode.' },
      { cmd: 'vlan 20', why: 'Creates VLAN 20 for the Engineering team.' },
      { cmd: 'name ENGINEERING', why: 'Names VLAN 20 for clarity.' },
      { cmd: 'exit', why: 'Returns to Global Configuration mode. Both VLANs must exist before assigning ports to them.' },
      { cmd: 'interface FastEthernet0/1', why: 'Enter interface config for Fa0/1. Ports are assigned one at a time.' },
      { cmd: 'switchport mode access', why: 'Explicitly sets the port to access mode — a port that belongs to exactly one VLAN.' },
      { cmd: 'switchport access vlan 10', why: 'Assigns Fa0/1 to VLAN 10 (SALES). The VLAN must already exist or this command will fail.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode to configure the next port.' },
      { cmd: 'interface FastEthernet0/2', why: 'Repeat for Fa0/2 — you must configure each port individually (no range support in this simulator).' },
      { cmd: 'switchport mode access', why: 'Set Fa0/2 to access mode.' },
      { cmd: 'switchport access vlan 10', why: 'Assign Fa0/2 to VLAN 10.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/7', why: 'Enter interface config for Fa0/7 — first port of the ENGINEERING group.' },
      { cmd: 'switchport mode access', why: 'Set Fa0/7 to access mode.' },
      { cmd: 'switchport access vlan 20', why: 'Assigns Fa0/7 to VLAN 20 (ENGINEERING).' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/8', why: 'Continue assigning ENGINEERING ports. Repeat this pattern through Fa0/12.' },
      { cmd: 'switchport mode access', why: 'Set Fa0/8 to access mode.' },
      { cmd: 'switchport access vlan 20', why: 'Assign Fa0/8 to VLAN 20.' },
      { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
      { cmd: 'show vlan brief', why: 'Confirms which ports belong to which VLANs. Fa0/1-6 should appear under VLAN 10, Fa0/7-12 under VLAN 20.' },
    ],
    validation: (state) => {
      const checks = [
        { label: 'VLAN 10 exists with name "SALES"', pass: state.vlans[10]?.name === 'SALES' },
        { label: 'VLAN 20 exists with name "ENGINEERING"', pass: state.vlans[20]?.name === 'ENGINEERING' },
        { label: 'Fa0/1 assigned to VLAN 10', pass: state.interfaces['FastEthernet0/1']?.accessVlan === 10 },
        { label: 'Fa0/7 assigned to VLAN 20', pass: state.interfaces['FastEthernet0/7']?.accessVlan === 20 },
      ];
      return checks;
    },
    initialState: null,
  },
  {
    id: 'trunk-config',
    title: 'Trunk Port Configuration',
    difficulty: 'Intermediate',
    duration: '10 min',
    description: 'Configure trunk ports on the GigabitEthernet uplinks for inter-switch VLAN traffic.',
    objectives: [
      'Create VLAN 10 (SALES) and VLAN 20 (ENGINEERING)',
      'Configure GigabitEthernet0/1 as a trunk port',
      'Configure GigabitEthernet0/2 as a trunk port',
      'Add descriptions to both trunk interfaces',
      'Verify with "show interfaces trunk"',
    ],
    hints: [
      'First create the VLANs in config mode',
      'Enter interface config: "interface gi0/1"',
      'Set trunk mode: "switchport mode trunk"',
      'Add description: "description Uplink to Core Switch"',
      'Repeat for Gi0/2, then verify with "show interfaces trunk"',
    ],
    commands: [
      { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
      { cmd: 'vlan 10', why: 'Create VLAN 10 — trunk ports carry all VLANs, so they must exist first.' },
      { cmd: 'name SALES', why: 'Name VLAN 10 for clarity.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'vlan 20', why: 'Create VLAN 20.' },
      { cmd: 'name ENGINEERING', why: 'Name VLAN 20.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface GigabitEthernet0/1', why: 'GigabitEthernet ports are typically used for uplinks because of their higher bandwidth.' },
      { cmd: 'switchport mode trunk', why: 'A trunk port carries traffic for multiple VLANs simultaneously using 802.1Q tagging.' },
      { cmd: 'description Uplink to Core Switch', why: 'Always document trunk ports so future admins know what is connected.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode to configure the second uplink.' },
      { cmd: 'interface GigabitEthernet0/2', why: 'Enter the second uplink interface.' },
      { cmd: 'switchport mode trunk', why: 'Configure Gi0/2 as a trunk port as well.' },
      { cmd: 'description Uplink to Distribution Switch', why: 'Document the second trunk link.' },
      { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
      { cmd: 'show interfaces trunk', why: 'Verifies both Gi0/1 and Gi0/2 are in trunking mode and shows allowed VLANs.' },
    ],
    validation: (state) => {
      return [
        { label: 'VLAN 10 exists', pass: !!state.vlans[10] },
        { label: 'VLAN 20 exists', pass: !!state.vlans[20] },
        { label: 'Gi0/1 is trunk', pass: state.interfaces['GigabitEthernet0/1']?.switchportMode === 'trunk' },
        { label: 'Gi0/2 is trunk', pass: state.interfaces['GigabitEthernet0/2']?.switchportMode === 'trunk' },
        { label: 'Gi0/1 has description', pass: !!state.interfaces['GigabitEthernet0/1']?.description },
        { label: 'Gi0/2 has description', pass: !!state.interfaces['GigabitEthernet0/2']?.description },
      ];
    },
    initialState: null,
  },
  {
    id: 'interface-management',
    title: 'Interface Management',
    difficulty: 'Beginner',
    duration: '10 min',
    description: 'Practice enabling, disabling, and configuring switch interfaces.',
    objectives: [
      'Shut down interfaces Fa0/20 through Fa0/24 (unused ports)',
      'Add a description to Fa0/1: "Server Room Link"',
      'Set Gi0/1 description to "Uplink to Router"',
      'Verify with "show ip interface brief"',
    ],
    hints: [
      'Enter interface config mode for each interface',
      'Use "shutdown" to disable a port',
      'Use "description Server Room Link" to add descriptions',
      'Use "show ip interface brief" to check status',
    ],
    commands: [
      { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/20', why: 'Target the first unused port to shut down.' },
      { cmd: 'shutdown', why: 'Administratively disables the port. Best practice: always shut down unused ports to prevent unauthorized access.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/21', why: 'Target the next unused port.' },
      { cmd: 'shutdown', why: 'Shut down Fa0/21.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/22', why: 'Target Fa0/22.' },
      { cmd: 'shutdown', why: 'Shut down Fa0/22.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/23', why: 'Target Fa0/23.' },
      { cmd: 'shutdown', why: 'Shut down Fa0/23.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/24', why: 'Target the last unused port.' },
      { cmd: 'shutdown', why: 'Shut down Fa0/24.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/1', why: 'Move to the port connected to the server room.' },
      { cmd: 'description Server Room Link', why: 'Labels this port in the config and show commands. Essential for troubleshooting in a real network.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface GigabitEthernet0/1', why: 'Move to the uplink port to add its description.' },
      { cmd: 'description Uplink to Router', why: 'Documents the uplink port for future reference.' },
      { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
      { cmd: 'show ip interface brief', why: 'Compact table showing every interface and its up/down status. Confirms shutdowns took effect.' },
    ],
    validation: (state) => {
      return [
        { label: 'Fa0/20 is shutdown', pass: state.interfaces['FastEthernet0/20']?.status === 'down' },
        { label: 'Fa0/24 is shutdown', pass: state.interfaces['FastEthernet0/24']?.status === 'down' },
        { label: 'Fa0/1 has description', pass: state.interfaces['FastEthernet0/1']?.description === 'Server Room Link' },
        { label: 'Gi0/1 has description', pass: state.interfaces['GigabitEthernet0/1']?.description === 'Uplink to Router' },
      ];
    },
    initialState: null,
  },
  {
    id: 'save-config',
    title: 'Save Configuration',
    difficulty: 'Beginner',
    duration: '5 min',
    description: 'Learn to save the running configuration to startup configuration.',
    objectives: [
      'Change the hostname to "LabSwitch"',
      'Create VLAN 100 named "MANAGEMENT"',
      'Save the configuration using "copy running-config startup-config"',
      'Verify with "show startup-config"',
    ],
    hints: [
      'Make your changes in config mode first',
      'Return to privileged EXEC mode with "end"',
      'Use "copy running-config startup-config" or "write memory"',
      'Verify with "show startup-config"',
    ],
    commands: [
      { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
      { cmd: 'hostname LabSwitch', why: 'Change the hostname as required by the lab.' },
      { cmd: 'vlan 100', why: 'Create VLAN 100 for the management network.' },
      { cmd: 'name MANAGEMENT', why: 'Name VLAN 100. The management VLAN is used for remote switch administration.' },
      { cmd: 'end', why: 'Return to Privileged EXEC. You must NOT be in config mode to run copy commands.' },
      { cmd: 'copy running-config startup-config', why: 'Saves the running config (in RAM) to startup config (in NVRAM). Without this, all changes are lost on reboot.' },
      { cmd: 'show startup-config', why: 'Confirms what will be loaded on the next reboot. Always verify after saving.' },
    ],
    validation: (state) => {
      return [
        { label: 'Hostname is "LabSwitch"', pass: state.hostname === 'LabSwitch' },
        { label: 'VLAN 100 exists', pass: !!state.vlans[100] },
        { label: 'Config saved', pass: !!state.startupConfig },
      ];
    },
    initialState: null,
  },
  {
    id: 'ssh-setup',
    title: 'SSH Remote Access Setup',
    difficulty: 'Intermediate',
    duration: '15 min',
    description: 'Configure secure remote management access via SSH. You will set a domain name, generate RSA keys, create a local user, and restrict VTY lines to SSH only.',
    objectives: [
      'Set the domain name to "lab.local"',
      'Generate RSA crypto keys (modulus 1024)',
      'Create local user "admin" with password "cisco123"',
      'Configure VTY lines to use local login and SSH only',
      'Verify with "show ip ssh"',
    ],
    hints: [
      'Set domain name first: "ip domain-name lab.local" in global config',
      'Generate keys: "crypto key generate rsa" — enter 1024 when prompted',
      'Create user: "username admin password cisco123"',
      'Enter "line vty 0 4" then "login local" then "transport input ssh"',
      'Verify SSH is enabled: "show ip ssh"',
    ],
    commands: [
      { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
      { cmd: 'ip domain-name lab.local', why: 'A domain name is required before RSA keys can be generated — it forms part of the key name (hostname.domain).' },
      { cmd: 'crypto key generate rsa', why: 'Generates the RSA key pair needed by SSH. Without keys, the SSH server cannot start.' },
      { cmd: 'username admin password cisco123', why: 'Creates a local user account. SSH with local login requires at least one username/password pair in the local database.' },
      { cmd: 'ip ssh version 2', why: 'Forces SSH version 2, which is more secure than version 1. Always specify v2 in production.' },
      { cmd: 'line vty 0 4', why: 'Enters configuration mode for the 5 virtual terminal lines used for remote sessions.' },
      { cmd: 'login local', why: 'Tells the VTY lines to authenticate using the local user database (the username/password you just created).' },
      { cmd: 'transport input ssh', why: 'Restricts remote access to SSH only — Telnet is blocked. This is a critical security setting.' },
      { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
      { cmd: 'show ip ssh', why: 'Confirms SSH is enabled, shows the version, and displays timeout/retry settings.' },
      { cmd: 'show running-config', why: 'Verify domain name, username, and VTY configuration all appear in the config.' },
    ],
    validation: (state) => [
      { label: 'Domain name is set', pass: !!state.domainName },
      { label: 'SSH version 2 configured', pass: state.sshVersion === 2 },
      { label: 'Local user "admin" created', pass: !!state.users?.admin },
      { label: 'VTY login local configured', pass: !!state.lines?.vty?.loginLocal },
      { label: 'VTY transport restricted to SSH', pass: state.lines?.vty?.transport === 'ssh' },
    ],
    initialState: null,
  },
  {
    id: 'port-security',
    title: 'Port Security',
    difficulty: 'Intermediate',
    duration: '15 min',
    description: 'Protect the network by limiting which MAC addresses can connect to specific switch ports. Configure port security on Fa0/1 and Fa0/2 with sticky MAC learning and shutdown violation mode.',
    objectives: [
      'Enable port security on Fa0/1',
      'Set maximum MAC addresses to 1 on Fa0/1',
      'Enable sticky MAC learning on Fa0/1',
      'Set violation mode to "shutdown" on Fa0/1',
      'Repeat port security configuration on Fa0/2',
    ],
    hints: [
      'Port must be in access mode before enabling port security',
      'Use "switchport port-security" to enable it',
      'Use "switchport port-security maximum 1" to allow only one device',
      'Use "switchport port-security mac-address sticky" for dynamic learning',
      'Use "switchport port-security violation shutdown" to shut down on violation',
    ],
    commands: [
      { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/1', why: 'Target the first port to secure.' },
      { cmd: 'switchport mode access', why: 'Port security only works on access ports — the port must not be in dynamic or trunk mode.' },
      { cmd: 'switchport port-security', why: 'Enables port security on this interface. No restrictions apply until you add more commands.' },
      { cmd: 'switchport port-security maximum 1', why: 'Limits the port to one MAC address. If a second device connects, the violation action triggers.' },
      { cmd: 'switchport port-security mac-address sticky', why: 'Dynamically learns the first MAC address and saves it to the config — no need to manually specify MAC addresses.' },
      { cmd: 'switchport port-security violation shutdown', why: 'The most strict violation mode — the port is err-disabled if an unauthorized MAC is detected. Use "no shutdown" to recover.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/2', why: 'Apply the same port security policy to Fa0/2.' },
      { cmd: 'switchport mode access', why: 'Ensure Fa0/2 is in access mode.' },
      { cmd: 'switchport port-security', why: 'Enable port security on Fa0/2.' },
      { cmd: 'switchport port-security maximum 1', why: 'Allow only one MAC address on Fa0/2.' },
      { cmd: 'switchport port-security mac-address sticky', why: 'Enable sticky learning on Fa0/2.' },
      { cmd: 'switchport port-security violation shutdown', why: 'Set shutdown as the violation action on Fa0/2.' },
      { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
      { cmd: 'show running-config', why: 'Verify port security settings appear on both Fa0/1 and Fa0/2.' },
    ],
    validation: (state) => [
      { label: 'Port security enabled on Fa0/1', pass: !!state.interfaces['FastEthernet0/1']?.portSecurityEnabled },
      { label: 'Fa0/1 maximum set to 1', pass: state.interfaces['FastEthernet0/1']?.portSecurityMaximum === 1 },
      { label: 'Fa0/1 sticky MAC learning enabled', pass: !!state.interfaces['FastEthernet0/1']?.portSecuritySticky },
      { label: 'Fa0/1 violation mode is shutdown', pass: state.interfaces['FastEthernet0/1']?.portSecurityViolation === 'shutdown' },
      { label: 'Port security enabled on Fa0/2', pass: !!state.interfaces['FastEthernet0/2']?.portSecurityEnabled },
    ],
    initialState: null,
  },
  {
    id: 'spanning-tree',
    title: 'Spanning Tree Protocol',
    difficulty: 'Intermediate',
    duration: '15 min',
    description: 'Configure Rapid PVST+, set bridge priority to make this switch the STP root for VLAN 10, and enable PortFast with BPDU Guard on access ports to speed up host convergence.',
    objectives: [
      'Change spanning-tree mode to "rapid-pvst"',
      'Create VLAN 10 named "DATA"',
      'Set STP root for VLAN 10 using bridge priority 4096',
      'Enable PortFast on Fa0/1',
      'Enable BPDU Guard on Fa0/1',
    ],
    hints: [
      'Change STP mode: "spanning-tree mode rapid-pvst" in global config',
      'Create VLAN 10 first before setting STP priority for it',
      'Set priority: "spanning-tree vlan 10 priority 4096" (must be a multiple of 4096)',
      'Enter Fa0/1 and use "spanning-tree portfast" to skip listening/learning states',
      'Add "spanning-tree bpduguard enable" on the same interface',
    ],
    commands: [
      { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
      { cmd: 'spanning-tree mode rapid-pvst', why: 'Rapid PVST+ converges much faster than classic PVST (seconds vs 30-50 seconds). Always use rapid-pvst in modern networks.' },
      { cmd: 'vlan 10', why: 'Create VLAN 10 — you must have the VLAN before configuring STP parameters for it.' },
      { cmd: 'name DATA', why: 'Name VLAN 10 for documentation.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'spanning-tree vlan 10 priority 4096', why: 'Sets the bridge priority for VLAN 10. Lower priority = preferred root. 4096 ensures this switch wins the root election for VLAN 10.' },
      { cmd: 'interface FastEthernet0/1', why: 'Enter the access port where hosts connect.' },
      { cmd: 'spanning-tree portfast', why: 'Skips the STP listening and learning states (normally 30 seconds total). Hosts get network access instantly. Only use on ports connected to end devices — NEVER on trunk ports.' },
      { cmd: 'spanning-tree bpduguard enable', why: 'Disables the port immediately if a BPDU is received — protects against someone plugging a rogue switch into this access port.' },
      { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
      { cmd: 'show spanning-tree', why: 'Verify this switch is the root bridge for VLAN 10 and the mode shows rapid-pvst.' },
      { cmd: 'show spanning-tree summary', why: 'Shows a high-level summary of STP mode and PortFast/BPDU Guard defaults.' },
    ],
    validation: (state) => [
      { label: 'Spanning-tree mode set to rapid-pvst', pass: state.spanningTreeMode === 'rapid-pvst' },
      { label: 'VLAN 10 exists with name "DATA"', pass: state.vlans[10]?.name === 'DATA' },
      { label: 'Fa0/1 PortFast enabled', pass: !!state.interfaces['FastEthernet0/1']?.spanningTreePortfast },
      { label: 'Fa0/1 BPDU Guard enabled', pass: !!state.interfaces['FastEthernet0/1']?.spanningTreeBpduguard },
    ],
    initialState: null,
  },
  {
    id: 'vtp-config',
    title: 'VTP Configuration',
    difficulty: 'Intermediate',
    duration: '10 min',
    description: 'Configure VLAN Trunking Protocol (VTP) to allow centralized VLAN management across multiple switches. Set up this switch as a VTP server with a domain and password.',
    objectives: [
      'Set VTP domain name to "CORP"',
      'Set VTP mode to "server"',
      'Set VTP password to "vtp123"',
      'Set VTP version to 2',
      'Verify with "show vtp status"',
    ],
    hints: [
      'All VTP commands start with "vtp" in global config mode',
      'Set domain first: "vtp domain CORP"',
      'Set mode: "vtp mode server"',
      'Set password: "vtp password vtp123"',
      'Verify: "show vtp status"',
    ],
    commands: [
      { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
      { cmd: 'vtp domain CORP', why: 'Sets the VTP domain name. All switches sharing VLANs via VTP must be in the same domain. VTP advertisements are only accepted from switches with matching domain names.' },
      { cmd: 'vtp mode server', why: 'Server mode allows creating, modifying and deleting VLANs. VTP servers propagate VLAN info to all clients in the domain.' },
      { cmd: 'vtp password vtp123', why: 'Adds a password to VTP advertisements. Switches must have the same password to accept VTP updates — prevents unauthorized switches from modifying VLANs.' },
      { cmd: 'vtp version 2', why: 'VTP version 2 supports Token Ring VLANs and has better consistency checking than version 1. Use v2 unless you have legacy requirements.' },
      { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
      { cmd: 'show vtp status', why: 'Displays VTP domain, mode, version, and revision number. Verify all settings are correct.' },
    ],
    validation: (state) => [
      { label: 'VTP domain set to "CORP"', pass: state.vtpDomain === 'CORP' },
      { label: 'VTP mode is server', pass: state.vtpMode === 'server' },
      { label: 'VTP password configured', pass: !!state.vtpPassword },
      { label: 'VTP version 2 configured', pass: state.vtpVersion === 2 },
    ],
    initialState: null,
  },
  {
    id: 'etherchannel',
    title: 'EtherChannel (LACP)',
    difficulty: 'Advanced',
    duration: '20 min',
    description: 'Bundle two GigabitEthernet uplinks into a single logical EtherChannel using LACP (802.3ad). This doubles bandwidth and provides link redundancy between switches.',
    objectives: [
      'Configure Gi0/1 in LACP active mode, channel-group 1',
      'Configure Gi0/2 in LACP active mode, channel-group 1',
      'Verify the EtherChannel bundle with "show etherchannel summary"',
    ],
    hints: [
      'Both interfaces must have identical configuration before bundling',
      'LACP active mode initiates negotiation: "channel-group 1 mode active"',
      'Apply the same command to both Gi0/1 and Gi0/2',
      'Verify with "show etherchannel summary" — look for the (SU) flag meaning layer2 + in-use',
    ],
    commands: [
      { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
      { cmd: 'interface GigabitEthernet0/1', why: 'Enter the first interface to bundle. Both uplinks must be in the same channel-group number.' },
      { cmd: 'channel-group 1 mode active', why: 'Assigns Gi0/1 to EtherChannel group 1 using LACP active mode. Active mode actively sends LACP packets to negotiate the bundle with the remote switch.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface GigabitEthernet0/2', why: 'Enter the second interface. It must join the same group (1) with the same LACP mode.' },
      { cmd: 'channel-group 1 mode active', why: 'Assigns Gi0/2 to group 1. Once both ports are in active mode, LACP negotiates the Port-Channel bundle automatically.' },
      { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
      { cmd: 'show etherchannel summary', why: 'Displays all EtherChannel groups, their member ports, and status flags. Look for (P) meaning bundled and (SU) on the Port-Channel meaning Layer2 and in-use.' },
      { cmd: 'show running-config', why: 'Verify both Gi0/1 and Gi0/2 show "channel-group 1 mode active".' },
    ],
    validation: (state) => [
      { label: 'Gi0/1 assigned to channel-group 1', pass: state.interfaces['GigabitEthernet0/1']?.channelGroup === 1 },
      { label: 'Gi0/1 LACP mode is active', pass: state.interfaces['GigabitEthernet0/1']?.channelGroupMode === 'active' },
      { label: 'Gi0/2 assigned to channel-group 1', pass: state.interfaces['GigabitEthernet0/2']?.channelGroup === 1 },
      { label: 'Gi0/2 LACP mode is active', pass: state.interfaces['GigabitEthernet0/2']?.channelGroupMode === 'active' },
    ],
    initialState: null,
  },
];

// ─── Troubleshooting Labs ───────────────────────────────────────────────────

export const troubleshootingScenarios = [
  {
    id: 'ts-port-shutdown',
    title: 'Port Won\'t Come Up',
    category: 'troubleshooting',
    difficulty: 'Beginner',
    duration: '10 min',
    description: 'A user reports their workstation lost network connectivity. Ports Fa0/3 and Fa0/5 are administratively shut down. Diagnose the problem and bring the ports back up.',
    objectives: [
      'Use "show ip interface brief" to identify shutdown ports',
      'Identify that Fa0/3 and Fa0/5 are administratively down',
      'Bring Fa0/3 back up with "no shutdown"',
      'Bring Fa0/5 back up with "no shutdown"',
      'Verify both ports are up',
    ],
    hints: [
      '"show ip interface brief" shows all ports and their status at a glance',
      'Look for "administratively down" in the Status column',
      'Enter interface config: "interface fa0/3" then "no shutdown"',
      'Repeat the process for Fa0/5',
    ],
    commands: [
      { cmd: 'show ip interface brief', why: 'First step in port troubleshooting — shows every interface status. "administratively down" means someone ran the shutdown command on it.' },
      { cmd: 'enable', why: 'You must be in Privileged EXEC mode to enter configuration mode.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode so you can modify interface settings.' },
      { cmd: 'interface FastEthernet0/3', why: 'Target the first broken port to fix it.' },
      { cmd: 'no shutdown', why: 'Administratively enables the port. The opposite of the "shutdown" command. The port will return to up/up.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/5', why: 'Target the second broken port.' },
      { cmd: 'no shutdown', why: 'Brings Fa0/5 back up.' },
      { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
      { cmd: 'show interfaces status', why: 'Confirms both ports now show "connected" status.' },
      { cmd: 'show ip interface brief', why: 'Second verification — both Fa0/3 and Fa0/5 should now show "up/up".' },
    ],
    validation: (state) => [
      { label: 'Checked interface status (show ip interface brief)', pass: !!state.viewedInterfaceBrief },
      { label: 'Fa0/3 is back up', pass: state.interfaces['FastEthernet0/3']?.status === 'up' },
      { label: 'Fa0/5 is back up', pass: state.interfaces['FastEthernet0/5']?.status === 'up' },
    ],
    initialState: (() => {
      const base = createDefaultSwitchState();
      return {
        ...base,
        interfaces: {
          ...base.interfaces,
          'FastEthernet0/3': { ...base.interfaces['FastEthernet0/3'], status: 'down' },
          'FastEthernet0/5': { ...base.interfaces['FastEthernet0/5'], status: 'down' },
        },
      };
    })(),
  },
  {
    id: 'ts-wrong-vlan',
    title: 'Device on Wrong VLAN',
    category: 'troubleshooting',
    difficulty: 'Intermediate',
    duration: '15 min',
    description: 'A workstation on Fa0/4 is on VLAN 99 (which doesn\'t exist), so it can\'t communicate. Fix the port assignment and verify connectivity.',
    objectives: [
      'Use "show vlan brief" to identify the misconfiguration',
      'Identify that Fa0/4 is assigned to non-existent VLAN 99',
      'Create VLAN 10 named "OFFICE"',
      'Move Fa0/4 to VLAN 10',
      'Verify with "show vlan brief"',
    ],
    hints: [
      '"show vlan brief" lists all VLANs and their port assignments',
      'A port on a non-existent VLAN will have its line protocol down',
      'Create the correct VLAN first with "vlan 10" then "name OFFICE"',
      'Then reassign the port: "interface fa0/4" → "switchport access vlan 10"',
    ],
    commands: [
      { cmd: 'show vlan brief', why: 'First look — lists all VLANs and their port members. Fa0/4 will NOT appear here because VLAN 99 does not exist.' },
      { cmd: 'show ip interface brief', why: 'Shows Fa0/4 line protocol is down — a dead giveaway that its assigned VLAN doesn\'t exist.' },
      { cmd: 'show interfaces FastEthernet0/4 switchport', why: 'Detailed switchport info for Fa0/4 — confirms the Access Mode VLAN is 99 and that VLAN does not exist.' },
      { cmd: 'enable', why: 'Enter Privileged EXEC mode to make configuration changes.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
      { cmd: 'vlan 10', why: 'Create VLAN 10 first — you cannot assign a port to a VLAN that doesn\'t exist.' },
      { cmd: 'name OFFICE', why: 'Always name VLANs for clarity and documentation.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/4', why: 'Enter interface config for the misconfigured port.' },
      { cmd: 'switchport mode access', why: 'Explicitly set the port to access mode before changing the VLAN assignment.' },
      { cmd: 'switchport access vlan 10', why: 'Moves the port from the non-existent VLAN 99 to VLAN 10, restoring connectivity.' },
      { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
      { cmd: 'show vlan brief', why: 'Confirm Fa0/4 now appears under VLAN 10.' },
      { cmd: 'show ip interface brief', why: 'Confirm Fa0/4 line protocol is now up/up.' },
    ],
    validation: (state) => [
      { label: 'VLAN 10 exists', pass: !!state.vlans[10] },
      { label: 'Fa0/4 is on VLAN 10', pass: state.interfaces['FastEthernet0/4']?.accessVlan === 10 },
      { label: 'Fa0/4 is not on the old broken VLAN 99', pass: state.interfaces['FastEthernet0/4']?.accessVlan !== 99 },
    ],
    initialState: (() => {
      const base = createDefaultSwitchState();
      return {
        ...base,
        interfaces: {
          ...base.interfaces,
          'FastEthernet0/4': { ...base.interfaces['FastEthernet0/4'], accessVlan: 99 },
        },
      };
    })(),
  },
  {
    id: 'ts-trunk-misconfigured',
    title: 'Trunk Link Not Carrying VLANs',
    category: 'troubleshooting',
    difficulty: 'Intermediate',
    duration: '15 min',
    description: 'Inter-VLAN traffic between switches is broken. Gi0/1 is set to access mode instead of trunk, and VLAN 10 and 20 are missing. Diagnose and fix the uplink.',
    objectives: [
      'Use "show interfaces trunk" to confirm no trunks are active',
      'Use "show interfaces Gi0/1 switchport" to see the misconfiguration',
      'Create VLAN 10 and VLAN 20',
      'Configure Gi0/1 as a trunk port',
      'Configure Gi0/2 as a trunk port',
      'Verify with "show interfaces trunk"',
    ],
    hints: [
      '"show interfaces trunk" shows only trunk ports — if it\'s empty, no trunks are configured',
      '"show ip interface brief" shows both Gi ports are up but not trunking',
      'Create VLANs first so the trunk has something to carry',
      'Set "switchport mode trunk" on each uplink interface',
    ],
    commands: [
      { cmd: 'show interfaces trunk', why: 'If this output is empty, no trunk ports exist — all inter-VLAN traffic between switches is blocked.' },
      { cmd: 'show ip interface brief', why: 'Confirms both Gi ports are physically up but not configured as trunks.' },
      { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
      { cmd: 'vlan 10', why: 'Create VLAN 10 — trunks carry VLANs that exist on the switch.' },
      { cmd: 'name DATA', why: 'Name VLAN 10 for clarity.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'vlan 20', why: 'Create VLAN 20.' },
      { cmd: 'name VOICE', why: 'Name VLAN 20.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface GigabitEthernet0/1', why: 'Enter the first uplink interface.' },
      { cmd: 'switchport mode trunk', why: 'Converts the port from access to trunk mode, allowing it to carry all VLANs.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface GigabitEthernet0/2', why: 'Enter the second uplink interface.' },
      { cmd: 'switchport mode trunk', why: 'Configure Gi0/2 as a trunk as well.' },
      { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
      { cmd: 'show interfaces trunk', why: 'Verify both Gi0/1 and Gi0/2 now appear in the trunk table.' },
    ],
    validation: (state) => [
      { label: 'VLAN 10 created', pass: !!state.vlans[10] },
      { label: 'VLAN 20 created', pass: !!state.vlans[20] },
      { label: 'Gi0/1 is configured as trunk', pass: state.interfaces['GigabitEthernet0/1']?.switchportMode === 'trunk' },
      { label: 'Gi0/2 is configured as trunk', pass: state.interfaces['GigabitEthernet0/2']?.switchportMode === 'trunk' },
    ],
    initialState: (() => {
      const base = createDefaultSwitchState();
      return {
        ...base,
        interfaces: {
          ...base.interfaces,
          'GigabitEthernet0/1': { ...base.interfaces['GigabitEthernet0/1'], switchportMode: 'access' },
          'GigabitEthernet0/2': { ...base.interfaces['GigabitEthernet0/2'], switchportMode: 'access' },
        },
      };
    })(),
  },
  {
    id: 'ts-svi-no-ip',
    title: 'Management IP Not Reachable',
    category: 'troubleshooting',
    difficulty: 'Intermediate',
    duration: '15 min',
    description: 'The network team can\'t SSH into the switch. The management VLAN interface (Vlan1) has no IP address configured. Set up remote management access.',
    objectives: [
      'Use "show ip interface brief" to see Vlan1 has no IP',
      'Assign IP address 192.168.1.10/24 to Vlan1',
      'Configure a default gateway of 192.168.1.1',
      'Set up VTY password "cisco123" and enable login',
      'Verify with "show running-config"',
    ],
    hints: [
      '"show ip interface brief" shows Vlan1 with "unassigned" for its IP',
      'Enter "interface vlan 1" then "ip address 192.168.1.10 255.255.255.0"',
      'Set the gateway in global config: "ip default-gateway 192.168.1.1"',
      'Configure VTY: "line vty 0 4" → "password cisco123" → "login"',
    ],
    commands: [
      { cmd: 'show ip interface brief', why: 'Confirms Vlan1 has "unassigned" IP — no IP means no remote management is possible.' },
      { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
      { cmd: 'interface vlan 1', why: 'The SVI (Switch Virtual Interface) for VLAN 1 is the management interface.' },
      { cmd: 'ip address 192.168.1.10 255.255.255.0', why: 'Assigns the management IP. Remote users SSH/Telnet to this address to reach the switch.' },
      { cmd: 'no shutdown', why: 'SVIs can be administratively down — always ensure the management interface is enabled.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'ip default-gateway 192.168.1.1', why: 'Without a default gateway, the switch can\'t route reply packets back to hosts on other subnets.' },
      { cmd: 'line vty 0 4', why: 'Configures the virtual terminal lines (0 through 4) for SSH/Telnet remote access.' },
      { cmd: 'password cisco123', why: 'Sets the VTY password required for remote login.' },
      { cmd: 'login', why: 'Enables password checking on the VTY lines. Without this, no password is required.' },
      { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
      { cmd: 'show running-config', why: 'Verify the Vlan1 IP, default gateway, and VTY configuration all appear correctly.' },
    ],
    validation: (state) => [
      { label: 'Vlan1 has an IP address', pass: state.interfaces['Vlan1']?.ipAddress && state.interfaces['Vlan1']?.ipAddress !== 'unassigned' },
      { label: 'Default gateway is set', pass: !!state.defaultGateway },
      { label: 'VTY password is configured', pass: !!state.lines?.vty?.password },
      { label: 'VTY login is enabled', pass: !!state.lines?.vty?.login },
    ],
    initialState: null,
  },
  {
    id: 'ts-duplicate-vlan',
    title: 'Native VLAN Mismatch',
    category: 'troubleshooting',
    difficulty: 'Advanced',
    duration: '20 min',
    description: 'Spanning tree is logging native VLAN mismatch errors on the Gi0/1 trunk. The trunk is configured but the native VLAN is set to 99 on one side. Fix the native VLAN to match the default (VLAN 1).',
    objectives: [
      'Use "show interfaces trunk" to inspect the trunk configuration',
      'Identify that Gi0/1 has native VLAN set to 99',
      'Correct the native VLAN back to VLAN 1',
      'Verify the fix with "show interfaces trunk"',
    ],
    hints: [
      '"show interfaces trunk" shows native VLAN per port in the first section',
      'The native VLAN must match on both ends of a trunk link',
      'Fix with: "switchport trunk native vlan 1" on the interface',
      'Or remove the override: "no switchport trunk native vlan" to reset to default',
    ],
    commands: [
      { cmd: 'show interfaces trunk', why: 'The "Native vlan" column reveals the mismatch — Gi0/1 shows 99, Gi0/2 shows 1. This causes STP errors and unexpected flooding.' },
      { cmd: 'show running-config', why: 'Confirms "switchport trunk native vlan 99" is explicitly set on Gi0/1.' },
      { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
      { cmd: 'interface GigabitEthernet0/1', why: 'Enter the misconfigured trunk interface.' },
      { cmd: 'switchport trunk native vlan 1', why: 'Resets the native VLAN to 1 (the default). Both ends of a trunk must use the same native VLAN.' },
      { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
      { cmd: 'show interfaces trunk', why: 'Verify the Native vlan column on Gi0/1 now shows 1, matching Gi0/2.' },
    ],
    validation: (state) => [
      { label: 'Gi0/1 is a trunk port', pass: state.interfaces['GigabitEthernet0/1']?.switchportMode === 'trunk' },
      { label: 'Gi0/1 native VLAN corrected to 1', pass: (state.interfaces['GigabitEthernet0/1']?.nativeVlan ?? 1) === 1 },
      { label: 'Gi0/2 is a trunk port', pass: state.interfaces['GigabitEthernet0/2']?.switchportMode === 'trunk' },
    ],
    initialState: (() => {
      const base = createDefaultSwitchState();
      return {
        ...base,
        vlans: { ...base.vlans, 10: { id: 10, name: 'DATA', status: 'active', ports: [] }, 20: { id: 20, name: 'VOICE', status: 'active', ports: [] } },
        interfaces: {
          ...base.interfaces,
          'GigabitEthernet0/1': { ...base.interfaces['GigabitEthernet0/1'], switchportMode: 'trunk', nativeVlan: 99 },
          'GigabitEthernet0/2': { ...base.interfaces['GigabitEthernet0/2'], switchportMode: 'trunk', nativeVlan: 1 },
        },
      };
    })(),
  },
  {
    id: 'ts-security-hardening',
    title: 'Security Hardening',
    category: 'troubleshooting',
    difficulty: 'Advanced',
    duration: '20 min',
    description: 'A security audit found several issues: no enable secret, unused ports are up, and CDP is enabled globally. Harden the switch configuration.',
    objectives: [
      'Set an enable secret password: "Str0ngPass!"',
      'Shut down all unused ports (Fa0/13 through Fa0/24)',
      'Disable CDP globally',
      'Save the hardened configuration',
    ],
    hints: [
      'Use "enable secret Str0ngPass!" in global config mode',
      'Enter each interface individually: "interface fa0/13" then "shutdown"',
      'Disable CDP with "no cdp run" in global config',
      'Save with "copy running-config startup-config"',
    ],
    commands: [
      { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
      { cmd: 'enable secret Str0ngPass!', why: 'Sets an MD5-encrypted enable password. Always prefer "enable secret" over "enable password" — the latter stores in reversible plaintext.' },
      { cmd: 'interface FastEthernet0/13', why: 'Target the first unused port. Best practice: shut down every port that has no device connected.' },
      { cmd: 'shutdown', why: 'Administratively disables Fa0/13. A shutdown port cannot be used by an attacker plugging in a rogue device.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/14', why: 'Shut down Fa0/14.' },
      { cmd: 'shutdown', why: 'Disable Fa0/14.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/15', why: 'Shut down Fa0/15.' },
      { cmd: 'shutdown', why: 'Disable Fa0/15.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/16', why: 'Shut down Fa0/16.' },
      { cmd: 'shutdown', why: 'Disable Fa0/16.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/17', why: 'Shut down Fa0/17.' },
      { cmd: 'shutdown', why: 'Disable Fa0/17.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/18', why: 'Shut down Fa0/18.' },
      { cmd: 'shutdown', why: 'Disable Fa0/18.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/19', why: 'Shut down Fa0/19.' },
      { cmd: 'shutdown', why: 'Disable Fa0/19.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/20', why: 'Shut down Fa0/20.' },
      { cmd: 'shutdown', why: 'Disable Fa0/20.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/21', why: 'Shut down Fa0/21.' },
      { cmd: 'shutdown', why: 'Disable Fa0/21.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/22', why: 'Shut down Fa0/22.' },
      { cmd: 'shutdown', why: 'Disable Fa0/22.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/23', why: 'Shut down Fa0/23.' },
      { cmd: 'shutdown', why: 'Disable Fa0/23.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/24', why: 'Shut down the last unused port, Fa0/24.' },
      { cmd: 'shutdown', why: 'Disable Fa0/24.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'no cdp run', why: 'CDP broadcasts device info (IOS version, model, IP) to neighbours. Disable it globally to prevent information disclosure on untrusted segments.' },
      { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
      { cmd: 'copy running-config startup-config', why: 'Persist the hardened config so all security settings survive a reboot.' },
      { cmd: 'show running-config', why: 'Verify the enable secret, shutdown interfaces, and "no cdp run" all appear correctly.' },
    ],
    validation: (state) => [
      { label: 'Enable secret is configured', pass: !!state.enableSecret },
      { label: 'Fa0/13 is shut down', pass: state.interfaces['FastEthernet0/13']?.status === 'down' },
      { label: 'Fa0/18 is shut down', pass: state.interfaces['FastEthernet0/18']?.status === 'down' },
      { label: 'Fa0/24 is shut down', pass: state.interfaces['FastEthernet0/24']?.status === 'down' },
      { label: 'CDP is disabled', pass: state.cdp === false },
      { label: 'Configuration saved', pass: !!state.startupConfig },
    ],
    initialState: null,
  },
];