import { createDefaultSwitchState } from './switchState';

// Helper to create a broken switch state for troubleshooting labs
function brokenState(overrides) {
  const base = createDefaultSwitchState();
  return { ...base, ...overrides };
}

export const scenarios = [
  {
    id: 'basic-navigation',
    title: 'CLI Navigation Basics',
    difficulty: 'Beginner',
    duration: '10 min',
    description: 'Learn to navigate between CLI modes: User EXEC, Privileged EXEC, and Global Configuration mode.',
    objectives: [
      'Enter Privileged EXEC mode using "enable"',
      'Enter Global Configuration mode using "configure terminal"',
      'Change the hostname to "MySwitch"',
      'Return to Privileged EXEC mode using "end"',
      'View the running configuration',
    ],
    hints: [
      'Start by typing "enable" to enter Privileged EXEC mode',
      'Use "configure terminal" or "conf t" to enter config mode',
      'Use "hostname MySwitch" to change the name',
      'Type "end" to return to Privileged EXEC',
      'Use "show running-config" to verify your changes',
    ],
    commands: [
      { cmd: 'enable', why: 'Moves from User EXEC (Switch>) to Privileged EXEC (Switch#). Required before making any configuration changes.' },
      { cmd: 'configure terminal', why: 'Enters Global Configuration mode (Switch(config)#). All device-wide settings are made from here.' },
      { cmd: 'hostname MySwitch', why: 'Changes the switch display name. The prompt immediately updates to reflect the new hostname.' },
      { cmd: 'end', why: 'Jumps directly back to Privileged EXEC from any config mode. Equivalent to pressing Ctrl+Z.' },
      { cmd: 'show running-config', why: 'Displays the active configuration in RAM. Use this to verify every change you make.' },
    ],
    validation: (state) => {
      return [
        { label: 'Enter Privileged EXEC mode using "enable"', pass: !!state.visitedPrivileged },
        { label: 'Enter Global Configuration mode using "configure terminal"', pass: !!state.visitedGlobalConfig },
        { label: 'Change the hostname to "MySwitch"', pass: state.hostname?.toLowerCase() === 'myswitch' },
        { label: 'Return to Privileged EXEC mode using "end"', pass: !!state.returnedToPrivileged },
        { label: 'View the running configuration', pass: !!state.viewedRunningConfig },
      ];
    },
    initialState: null,
  },
  {
    id: 'vlan-config',
    title: 'VLAN Configuration',
    difficulty: 'Intermediate',
    duration: '15 min',
    description: 'Create VLANs and assign ports to different VLANs for network segmentation.',
    objectives: [
      'Create VLAN 10 and name it "SALES"',
      'Create VLAN 20 and name it "ENGINEERING"',
      'Assign FastEthernet0/1 through Fa0/6 to VLAN 10',
      'Assign FastEthernet0/7 through Fa0/12 to VLAN 20',
      'Verify with "show vlan brief"',
    ],
    hints: [
      'Enter config mode, then use "vlan 10" to create a VLAN',
      'Use "name SALES" inside VLAN config mode, then "exit" back to global config',
      'Use "interface fa0/1" then "switchport mode access" then "switchport access vlan 10"',
      'Repeat for each port you want to assign',
      'Use "show vlan brief" to verify assignments',
    ],
    commands: [
      { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode to start making changes.' },
      { cmd: 'vlan 10', why: 'Creates VLAN 10 and enters VLAN config mode. VLANs segment a switch into isolated broadcast domains.' },
      { cmd: 'name SALES', why: 'Assigns a human-readable name to VLAN 10.' },
      { cmd: 'exit', why: 'Returns from VLAN config mode back to Global Configuration mode.' },
      { cmd: 'vlan 20', why: 'Creates VLAN 20 for the Engineering team.' },
      { cmd: 'name ENGINEERING', why: 'Names VLAN 20 for clarity.' },
      { cmd: 'exit', why: 'Returns to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/1', why: 'Enters interface configuration mode for port Fa0/1.' },
      { cmd: 'switchport mode access', why: 'Explicitly sets the port to access mode — a port that belongs to a single VLAN.' },
      { cmd: 'switchport access vlan 10', why: 'Assigns this port to VLAN 10. Any device plugged in here will be on the SALES network.' },
      { cmd: 'exit', why: 'Returns to Global Configuration mode to configure the next port.' },
      { cmd: 'interface FastEthernet0/7', why: 'Enters interface config mode for Fa0/7 to assign it to VLAN 20.' },
      { cmd: 'switchport mode access', why: 'Sets Fa0/7 to access mode.' },
      { cmd: 'switchport access vlan 20', why: 'Assigns Fa0/7 to VLAN 20 (ENGINEERING).' },
      { cmd: 'end', why: 'Returns to Privileged EXEC mode.' },
      { cmd: 'show vlan brief', why: 'Confirms which ports belong to which VLANs. Run this after every assignment to verify.' },
    ],
    validation: (state) => {
      const checks = [
        { label: 'VLAN 10 exists with name "SALES"', pass: state.vlans[10]?.name === 'SALES' },
        { label: 'VLAN 20 exists with name "ENGINEERING"', pass: state.vlans[20]?.name === 'ENGINEERING' },
        { label: 'Fa0/1 assigned to VLAN 10', pass: state.interfaces['FastEthernet0/1']?.accessVlan === 10 },
        { label: 'Fa0/7 assigned to VLAN 20', pass: state.interfaces['FastEthernet0/7']?.accessVlan === 20 },
      ];
      return checks;
    },
    initialState: null,
  },
  {
    id: 'trunk-config',
    title: 'Trunk Port Configuration',
    difficulty: 'Intermediate',
    duration: '10 min',
    description: 'Configure trunk ports on the GigabitEthernet uplinks for inter-switch VLAN traffic.',
    objectives: [
      'Create VLAN 10 (SALES) and VLAN 20 (ENGINEERING)',
      'Configure GigabitEthernet0/1 as a trunk port',
      'Configure GigabitEthernet0/2 as a trunk port',
      'Add descriptions to both trunk interfaces',
      'Verify with "show interfaces trunk"',
    ],
    hints: [
      'First create the VLANs in config mode',
      'Enter interface config: "interface gi0/1"',
      'Set trunk mode: "switchport mode trunk"',
      'Add description: "description Uplink to Core Switch"',
      'Repeat for Gi0/2, then verify with "show interfaces trunk"',
    ],
    commands: [
      { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
      { cmd: 'vlan 10', why: 'Create VLAN 10 — trunk ports carry all VLANs, so they must exist first.' },
      { cmd: 'name SALES', why: 'Name VLAN 10 for clarity.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'vlan 20', why: 'Create VLAN 20.' },
      { cmd: 'name ENGINEERING', why: 'Name VLAN 20.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface GigabitEthernet0/1', why: 'GigabitEthernet ports are typically used for uplinks because of their higher bandwidth.' },
      { cmd: 'switchport mode trunk', why: 'A trunk port carries traffic for multiple VLANs simultaneously using 802.1Q tagging.' },
      { cmd: 'description Uplink to Core Switch', why: 'Always document trunk ports so future admins know what is connected.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode to configure the second uplink.' },
      { cmd: 'interface GigabitEthernet0/2', why: 'Enter the second uplink interface.' },
      { cmd: 'switchport mode trunk', why: 'Configure Gi0/2 as a trunk port as well.' },
      { cmd: 'description Uplink to Distribution Switch', why: 'Document the second trunk link.' },
      { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
      { cmd: 'show interfaces trunk', why: 'Verifies both Gi0/1 and Gi0/2 are in trunking mode and shows allowed VLANs.' },
    ],
    validation: (state) => {
      return [
        { label: 'VLAN 10 exists', pass: !!state.vlans[10] },
        { label: 'VLAN 20 exists', pass: !!state.vlans[20] },
        { label: 'Gi0/1 is trunk', pass: state.interfaces['GigabitEthernet0/1']?.switchportMode === 'trunk' },
        { label: 'Gi0/2 is trunk', pass: state.interfaces['GigabitEthernet0/2']?.switchportMode === 'trunk' },
        { label: 'Gi0/1 has description', pass: !!state.interfaces['GigabitEthernet0/1']?.description },
        { label: 'Gi0/2 has description', pass: !!state.interfaces['GigabitEthernet0/2']?.description },
      ];
    },
    initialState: null,
  },
  {
    id: 'interface-management',
    title: 'Interface Management',
    difficulty: 'Beginner',
    duration: '10 min',
    description: 'Practice enabling, disabling, and configuring switch interfaces.',
    objectives: [
      'Shut down interfaces Fa0/20 through Fa0/24 (unused ports)',
      'Add a description to Fa0/1: "Server Room Link"',
      'Set Gi0/1 description to "Uplink to Router"',
      'Verify with "show ip interface brief"',
    ],
    hints: [
      'Enter interface config mode for each interface',
      'Use "shutdown" to disable a port',
      'Use "description Server Room Link" to add descriptions',
      'Use "show ip interface brief" to check status',
    ],
    commands: [
      { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/20', why: 'Target the first unused port to shut down.' },
      { cmd: 'shutdown', why: 'Administratively disables the port. Best practice: always shut down unused ports to prevent unauthorized access.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/21', why: 'Target the next unused port.' },
      { cmd: 'shutdown', why: 'Shut down Fa0/21.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/22', why: 'Target Fa0/22.' },
      { cmd: 'shutdown', why: 'Shut down Fa0/22.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/23', why: 'Target Fa0/23.' },
      { cmd: 'shutdown', why: 'Shut down Fa0/23.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/24', why: 'Target the last unused port.' },
      { cmd: 'shutdown', why: 'Shut down Fa0/24.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/1', why: 'Move to the port connected to the server room.' },
      { cmd: 'description Server Room Link', why: 'Labels this port in the config and show commands. Essential for troubleshooting in a real network.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface GigabitEthernet0/1', why: 'Move to the uplink port to add its description.' },
      { cmd: 'description Uplink to Router', why: 'Documents the uplink port for future reference.' },
      { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
      { cmd: 'show ip interface brief', why: 'Compact table showing every interface and its up/down status. Confirms shutdowns took effect.' },
    ],
    validation: (state) => {
      return [
        { label: 'Fa0/20 is shutdown', pass: state.interfaces['FastEthernet0/20']?.status === 'down' },
        { label: 'Fa0/24 is shutdown', pass: state.interfaces['FastEthernet0/24']?.status === 'down' },
        { label: 'Fa0/1 has description', pass: state.interfaces['FastEthernet0/1']?.description === 'Server Room Link' },
        { label: 'Gi0/1 has description', pass: state.interfaces['GigabitEthernet0/1']?.description === 'Uplink to Router' },
      ];
    },
    initialState: null,
  },
  {
    id: 'save-config',
    title: 'Save Configuration',
    difficulty: 'Beginner',
    duration: '5 min',
    description: 'Learn to save the running configuration to startup configuration.',
    objectives: [
      'Change the hostname to "LabSwitch"',
      'Create VLAN 100 named "MANAGEMENT"',
      'Save the configuration using "copy running-config startup-config"',
      'Verify with "show startup-config"',
    ],
    hints: [
      'Make your changes in config mode first',
      'Return to privileged EXEC mode with "end"',
      'Use "copy running-config startup-config" or "write memory"',
      'Verify with "show startup-config"',
    ],
    commands: [
      { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
      { cmd: 'hostname LabSwitch', why: 'Change the hostname as required by the lab.' },
      { cmd: 'vlan 100', why: 'Create VLAN 100 for the management network.' },
      { cmd: 'name MANAGEMENT', why: 'Name VLAN 100. The management VLAN is used for remote switch administration.' },
      { cmd: 'end', why: 'Return to Privileged EXEC. You must NOT be in config mode to run copy commands.' },
      { cmd: 'copy running-config startup-config', why: 'Saves the running config (in RAM) to startup config (in NVRAM). Without this, all changes are lost on reboot.' },
      { cmd: 'show startup-config', why: 'Confirms what will be loaded on the next reboot. Always verify after saving.' },
    ],
    validation: (state) => {
      return [
        { label: 'Hostname is "LabSwitch"', pass: state.hostname === 'LabSwitch' },
        { label: 'VLAN 100 exists', pass: !!state.vlans[100] },
        { label: 'Config saved', pass: !!state.startupConfig },
      ];
    },
    initialState: null,
  },
];

// ─── Troubleshooting Labs ───────────────────────────────────────────────────

export const troubleshootingScenarios = [
  {
    id: 'ts-port-shutdown',
    title: 'Port Won\'t Come Up',
    category: 'troubleshooting',
    difficulty: 'Beginner',
    duration: '10 min',
    description: 'A user reports their workstation lost network connectivity. Ports Fa0/3 and Fa0/5 are administratively shut down. Diagnose the problem and bring the ports back up.',
    objectives: [
      'Use "show ip interface brief" to identify shutdown ports',
      'Identify that Fa0/3 and Fa0/5 are administratively down',
      'Bring Fa0/3 back up with "no shutdown"',
      'Bring Fa0/5 back up with "no shutdown"',
      'Verify both ports are up',
    ],
    hints: [
      '"show ip interface brief" shows all ports and their status at a glance',
      'Look for "administratively down" in the Status column',
      'Enter interface config: "interface fa0/3" then "no shutdown"',
      'Repeat the process for Fa0/5',
    ],
    commands: [
      { cmd: 'show ip interface brief', why: 'First step in port troubleshooting — shows every interface status. "administratively down" means someone ran the shutdown command on it.' },
      { cmd: 'enable', why: 'You must be in Privileged EXEC mode to enter configuration mode.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode so you can modify interface settings.' },
      { cmd: 'interface FastEthernet0/3', why: 'Target the first broken port to fix it.' },
      { cmd: 'no shutdown', why: 'Administratively enables the port. The opposite of the "shutdown" command. The port will return to up/up.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/5', why: 'Target the second broken port.' },
      { cmd: 'no shutdown', why: 'Brings Fa0/5 back up.' },
      { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
      { cmd: 'show interfaces status', why: 'Confirms both ports now show "connected" status.' },
      { cmd: 'show ip interface brief', why: 'Second verification — both Fa0/3 and Fa0/5 should now show "up/up".' },
    ],
    validation: (state) => [
      { label: 'Checked interface status (show ip interface brief)', pass: !!state.viewedInterfaceBrief },
      { label: 'Fa0/3 is back up', pass: state.interfaces['FastEthernet0/3']?.status === 'up' },
      { label: 'Fa0/5 is back up', pass: state.interfaces['FastEthernet0/5']?.status === 'up' },
    ],
    initialState: (() => {
      const base = createDefaultSwitchState();
      return {
        ...base,
        interfaces: {
          ...base.interfaces,
          'FastEthernet0/3': { ...base.interfaces['FastEthernet0/3'], status: 'down' },
          'FastEthernet0/5': { ...base.interfaces['FastEthernet0/5'], status: 'down' },
        },
      };
    })(),
  },
  {
    id: 'ts-wrong-vlan',
    title: 'Device on Wrong VLAN',
    category: 'troubleshooting',
    difficulty: 'Intermediate',
    duration: '15 min',
    description: 'A workstation on Fa0/4 is on VLAN 99 (which doesn\'t exist), so it can\'t communicate. Fix the port assignment and verify connectivity.',
    objectives: [
      'Use "show vlan brief" to identify the misconfiguration',
      'Identify that Fa0/4 is assigned to non-existent VLAN 99',
      'Create VLAN 10 named "OFFICE"',
      'Move Fa0/4 to VLAN 10',
      'Verify with "show vlan brief"',
    ],
    hints: [
      '"show vlan brief" lists all VLANs and their port assignments',
      'A port on a non-existent VLAN will have its line protocol down',
      'Create the correct VLAN first with "vlan 10" then "name OFFICE"',
      'Then reassign the port: "interface fa0/4" → "switchport access vlan 10"',
    ],
    commands: [
      { cmd: 'show vlan brief', why: 'Shows all VLAN memberships. If a port\'s VLAN doesn\'t appear in this list, traffic will be dropped.' },
      { cmd: 'show ip interface brief', why: 'Shows Fa0/4 line protocol is down because its VLAN 99 doesn\'t exist.' },
      { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
      { cmd: 'vlan 10', why: 'Create the correct VLAN. A port assigned to a non-existent VLAN is effectively disconnected.' },
      { cmd: 'name OFFICE', why: 'Always name VLANs for clarity and documentation.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/4', why: 'Target the misconfigured port.' },
      { cmd: 'switchport mode access', why: 'Confirms the port is in access mode before assigning a VLAN.' },
      { cmd: 'switchport access vlan 10', why: 'Reassigns the port from the non-existent VLAN 99 to VLAN 10, restoring connectivity.' },
      { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
      { cmd: 'show vlan brief', why: 'Confirm Fa0/4 now appears under VLAN 10 instead of VLAN 99.' },
    ],
    validation: (state) => [
      { label: 'VLAN 10 exists', pass: !!state.vlans[10] },
      { label: 'Fa0/4 is on VLAN 10', pass: state.interfaces['FastEthernet0/4']?.accessVlan === 10 },
      { label: 'Fa0/4 is not on the old broken VLAN 99', pass: state.interfaces['FastEthernet0/4']?.accessVlan !== 99 },
    ],
    initialState: (() => {
      const base = createDefaultSwitchState();
      return {
        ...base,
        interfaces: {
          ...base.interfaces,
          'FastEthernet0/4': { ...base.interfaces['FastEthernet0/4'], accessVlan: 99 },
        },
      };
    })(),
  },
  {
    id: 'ts-trunk-misconfigured',
    title: 'Trunk Link Not Carrying VLANs',
    category: 'troubleshooting',
    difficulty: 'Intermediate',
    duration: '15 min',
    description: 'Inter-VLAN traffic between switches is broken. Gi0/1 is set to access mode instead of trunk, and VLAN 10 and 20 are missing. Diagnose and fix the uplink.',
    objectives: [
      'Use "show interfaces trunk" to confirm no trunks are active',
      'Use "show interfaces Gi0/1 switchport" to see the misconfiguration',
      'Create VLAN 10 and VLAN 20',
      'Configure Gi0/1 as a trunk port',
      'Configure Gi0/2 as a trunk port',
      'Verify with "show interfaces trunk"',
    ],
    hints: [
      '"show interfaces trunk" shows only trunk ports — if it\'s empty, no trunks are configured',
      '"show ip interface brief" shows both Gi ports are up but not trunking',
      'Create VLANs first so the trunk has something to carry',
      'Set "switchport mode trunk" on each uplink interface',
    ],
    commands: [
      { cmd: 'show interfaces trunk', why: 'If this output is empty, no trunk ports exist — all inter-VLAN traffic between switches is blocked.' },
      { cmd: 'show ip interface brief', why: 'Confirms both Gi ports are physically up but not configured as trunks.' },
      { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
      { cmd: 'vlan 10', why: 'Create VLAN 10 — trunks carry VLANs that exist on the switch.' },
      { cmd: 'name DATA', why: 'Name VLAN 10 for clarity.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'vlan 20', why: 'Create VLAN 20.' },
      { cmd: 'name VOICE', why: 'Name VLAN 20.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface GigabitEthernet0/1', why: 'Enter the first uplink interface.' },
      { cmd: 'switchport mode trunk', why: 'Converts the port from access to trunk mode, allowing it to carry all VLANs.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface GigabitEthernet0/2', why: 'Enter the second uplink interface.' },
      { cmd: 'switchport mode trunk', why: 'Configure Gi0/2 as a trunk as well.' },
      { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
      { cmd: 'show interfaces trunk', why: 'Verify both Gi0/1 and Gi0/2 now appear in the trunk table.' },
    ],
    validation: (state) => [
      { label: 'VLAN 10 created', pass: !!state.vlans[10] },
      { label: 'VLAN 20 created', pass: !!state.vlans[20] },
      { label: 'Gi0/1 is configured as trunk', pass: state.interfaces['GigabitEthernet0/1']?.switchportMode === 'trunk' },
      { label: 'Gi0/2 is configured as trunk', pass: state.interfaces['GigabitEthernet0/2']?.switchportMode === 'trunk' },
    ],
    initialState: (() => {
      const base = createDefaultSwitchState();
      return {
        ...base,
        interfaces: {
          ...base.interfaces,
          'GigabitEthernet0/1': { ...base.interfaces['GigabitEthernet0/1'], switchportMode: 'access' },
          'GigabitEthernet0/2': { ...base.interfaces['GigabitEthernet0/2'], switchportMode: 'access' },
        },
      };
    })(),
  },
  {
    id: 'ts-svi-no-ip',
    title: 'Management IP Not Reachable',
    category: 'troubleshooting',
    difficulty: 'Intermediate',
    duration: '15 min',
    description: 'The network team can\'t SSH into the switch. The management VLAN interface (Vlan1) has no IP address configured. Set up remote management access.',
    objectives: [
      'Use "show ip interface brief" to see Vlan1 has no IP',
      'Assign IP address 192.168.1.10/24 to Vlan1',
      'Configure a default gateway of 192.168.1.1',
      'Set up VTY password "cisco123" and enable login',
      'Verify with "show running-config"',
    ],
    hints: [
      '"show ip interface brief" shows Vlan1 with "unassigned" for its IP',
      'Enter "interface vlan 1" then "ip address 192.168.1.10 255.255.255.0"',
      'Set the gateway in global config: "ip default-gateway 192.168.1.1"',
      'Configure VTY: "line vty 0 4" → "password cisco123" → "login"',
    ],
    commands: [
      { cmd: 'show ip interface brief', why: 'Confirms Vlan1 has "unassigned" IP — no IP means no remote management is possible.' },
      { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
      { cmd: 'interface vlan 1', why: 'The SVI (Switch Virtual Interface) for VLAN 1 is the management interface.' },
      { cmd: 'ip address 192.168.1.10 255.255.255.0', why: 'Assigns the management IP. Remote users SSH/Telnet to this address to reach the switch.' },
      { cmd: 'no shutdown', why: 'SVIs can be administratively down — always ensure the management interface is enabled.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'ip default-gateway 192.168.1.1', why: 'Without a default gateway, the switch can\'t route reply packets back to hosts on other subnets.' },
      { cmd: 'line vty 0 4', why: 'Configures the virtual terminal lines (0 through 4) for SSH/Telnet remote access.' },
      { cmd: 'password cisco123', why: 'Sets the VTY password required for remote login.' },
      { cmd: 'login', why: 'Enables password checking on the VTY lines. Without this, no password is required.' },
      { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
      { cmd: 'show running-config', why: 'Verify the Vlan1 IP, default gateway, and VTY configuration all appear correctly.' },
    ],
    validation: (state) => [
      { label: 'Vlan1 has an IP address', pass: state.interfaces['Vlan1']?.ipAddress && state.interfaces['Vlan1']?.ipAddress !== 'unassigned' },
      { label: 'Default gateway is set', pass: !!state.defaultGateway },
      { label: 'VTY password is configured', pass: !!state.lines?.vty?.password },
      { label: 'VTY login is enabled', pass: !!state.lines?.vty?.login },
    ],
    initialState: null,
  },
  {
    id: 'ts-duplicate-vlan',
    title: 'Native VLAN Mismatch',
    category: 'troubleshooting',
    difficulty: 'Advanced',
    duration: '20 min',
    description: 'Spanning tree is logging native VLAN mismatch errors on the Gi0/1 trunk. The trunk is configured but the native VLAN is set to 99 on one side. Fix the native VLAN to match the default (VLAN 1).',
    objectives: [
      'Use "show interfaces trunk" to inspect the trunk configuration',
      'Identify that Gi0/1 has native VLAN set to 99',
      'Correct the native VLAN back to VLAN 1',
      'Verify the fix with "show interfaces trunk"',
    ],
    hints: [
      '"show interfaces trunk" shows native VLAN per port in the first section',
      'The native VLAN must match on both ends of a trunk link',
      'Fix with: "switchport trunk native vlan 1" on the interface',
      'Or remove the override: "no switchport trunk native vlan" to reset to default',
    ],
    commands: [
      { cmd: 'show interfaces trunk', why: 'The "Native vlan" column reveals the mismatch — Gi0/1 shows 99, Gi0/2 shows 1. This causes STP errors and unexpected flooding.' },
      { cmd: 'show running-config', why: 'Confirms "switchport trunk native vlan 99" is explicitly set on Gi0/1.' },
      { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
      { cmd: 'interface GigabitEthernet0/1', why: 'Enter the misconfigured trunk interface.' },
      { cmd: 'switchport trunk native vlan 1', why: 'Resets the native VLAN to 1 (the default). Both ends of a trunk must use the same native VLAN.' },
      { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
      { cmd: 'show interfaces trunk', why: 'Verify the Native vlan column on Gi0/1 now shows 1, matching Gi0/2.' },
    ],
    validation: (state) => [
      { label: 'Gi0/1 is a trunk port', pass: state.interfaces['GigabitEthernet0/1']?.switchportMode === 'trunk' },
      { label: 'Gi0/1 native VLAN corrected to 1', pass: (state.interfaces['GigabitEthernet0/1']?.nativeVlan ?? 1) === 1 },
      { label: 'Gi0/2 is a trunk port', pass: state.interfaces['GigabitEthernet0/2']?.switchportMode === 'trunk' },
    ],
    initialState: (() => {
      const base = createDefaultSwitchState();
      return {
        ...base,
        vlans: { ...base.vlans, 10: { id: 10, name: 'DATA', status: 'active', ports: [] }, 20: { id: 20, name: 'VOICE', status: 'active', ports: [] } },
        interfaces: {
          ...base.interfaces,
          'GigabitEthernet0/1': { ...base.interfaces['GigabitEthernet0/1'], switchportMode: 'trunk', nativeVlan: 99 },
          'GigabitEthernet0/2': { ...base.interfaces['GigabitEthernet0/2'], switchportMode: 'trunk', nativeVlan: 1 },
        },
      };
    })(),
  },
  {
    id: 'ts-security-hardening',
    title: 'Security Hardening',
    category: 'troubleshooting',
    difficulty: 'Advanced',
    duration: '20 min',
    description: 'A security audit found several issues: no enable secret, unused ports are up, and CDP is enabled globally. Harden the switch configuration.',
    objectives: [
      'Set an enable secret password: "Str0ngPass!"',
      'Shut down all unused ports (Fa0/13 through Fa0/24)',
      'Disable CDP globally',
      'Save the hardened configuration',
    ],
    hints: [
      'Use "enable secret Str0ngPass!" in global config mode',
      'Enter each interface individually: "interface fa0/13" then "shutdown"',
      'Disable CDP with "no cdp run" in global config',
      'Save with "copy running-config startup-config"',
    ],
    commands: [
      { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
      { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
      { cmd: 'enable secret Str0ngPass!', why: 'The enable secret is MD5-encrypted in the config — always prefer it over "enable password" which stores in plaintext.' },
      { cmd: 'interface FastEthernet0/13', why: 'Target first unused port. Industry best practice: shut down all unused switch ports to prevent unauthorized device connections.' },
      { cmd: 'shutdown', why: 'Administratively disables the port. A shutdown port cannot be used by an attacker plugging in a device.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/14', why: 'Continue shutting down unused ports.' },
      { cmd: 'shutdown', why: 'Shut down Fa0/14.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/18', why: 'Shut down additional unused ports (repeat this pattern for Fa0/15 through Fa0/24).' },
      { cmd: 'shutdown', why: 'Shut down Fa0/18.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'interface FastEthernet0/24', why: 'Shut down the last unused port.' },
      { cmd: 'shutdown', why: 'Shut down Fa0/24.' },
      { cmd: 'exit', why: 'Return to Global Configuration mode.' },
      { cmd: 'no cdp run', why: 'CDP (Cisco Discovery Protocol) broadcasts device info including IOS version and model. Disable it on untrusted segments to prevent information disclosure.' },
      { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
      { cmd: 'copy running-config startup-config', why: 'Persist the hardened config so all security settings survive a reboot.' },
      { cmd: 'show running-config', why: 'Verify the enable secret, shutdown ports, and CDP disabled status all appear in the config.' },
    ],
    validation: (state) => [
      { label: 'Enable secret is configured', pass: !!state.enableSecret },
      { label: 'Fa0/13 is shut down', pass: state.interfaces['FastEthernet0/13']?.status === 'down' },
      { label: 'Fa0/18 is shut down', pass: state.interfaces['FastEthernet0/18']?.status === 'down' },
      { label: 'Fa0/24 is shut down', pass: state.interfaces['FastEthernet0/24']?.status === 'down' },
      { label: 'CDP is disabled', pass: state.cdp === false },
      { label: 'Configuration saved', pass: !!state.startupConfig },
    ],
    initialState: null,
  },
];