import { createDefaultSwitchState } from '../../switchState';

export default {
  id: 'test-office-vlan',
  title: 'Office VLAN Deployment',
  category: 'test',
  difficulty: 'Intermediate',
  duration: '25 min',
  description: 'A small office needs three VLANs: SALES (VLAN 10), HR (VLAN 20), and MGMT (VLAN 99). You must create the VLANs, assign ports, configure the management SVI with an IP address, and save the configuration.',
  objectives: [
    'Create VLAN 10 named SALES',
    'Create VLAN 20 named HR',
    'Create VLAN 99 named MGMT',
    'Assign Fa0/1–Fa0/5 to VLAN 10 (SALES)',
    'Assign Fa0/6–Fa0/10 to VLAN 20 (HR)',
    'Configure Vlan99 SVI with IP 192.168.99.1 255.255.255.0',
    'Set default gateway to 192.168.99.254',
    'Save the running configuration',
  ],
  hints: [
    'Create VLANs one at a time: "vlan 10" then "name SALES" inside vlan config mode',
    'To assign ports, enter each interface and use "switchport mode access" then "switchport access vlan 10"',
    'The SVI is configured with "interface vlan 99" then "ip address 192.168.99.1 255.255.255.0" and "no shutdown"',
    'Default gateway is set in global config: "ip default-gateway 192.168.99.254"',
    'Save with "copy running-config startup-config" or "write memory"',
  ],
  commands: [
    { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
    { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
    { cmd: 'vlan 10', why: 'Create VLAN 10 — enters VLAN config mode.' },
    { cmd: 'name SALES', why: 'Assign a human-readable name to VLAN 10.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'vlan 20', why: 'Create VLAN 20.' },
    { cmd: 'name HR', why: 'Name VLAN 20.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'vlan 99', why: 'Create management VLAN 99.' },
    { cmd: 'name MGMT', why: 'Name VLAN 99.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/1', why: 'Enter interface config for Fa0/1 to assign to VLAN 10.' },
    { cmd: 'switchport mode access', why: 'Force the port into access (not trunk) mode.' },
    { cmd: 'switchport access vlan 10', why: 'Assign Fa0/1 to VLAN 10 (SALES).' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/2', why: 'Repeat for each port in the SALES group.' },
    { cmd: 'switchport mode access', why: 'Set access mode.' },
    { cmd: 'switchport access vlan 10', why: 'Assign Fa0/2 to VLAN 10.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/3', why: 'Repeat for Fa0/3.' },
    { cmd: 'switchport mode access', why: 'Set access mode.' },
    { cmd: 'switchport access vlan 10', why: 'Assign Fa0/3 to VLAN 10.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/4', why: 'Repeat for Fa0/4.' },
    { cmd: 'switchport mode access', why: 'Set access mode.' },
    { cmd: 'switchport access vlan 10', why: 'Assign Fa0/4 to VLAN 10.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/5', why: 'Last port in the SALES group.' },
    { cmd: 'switchport mode access', why: 'Set access mode.' },
    { cmd: 'switchport access vlan 10', why: 'Assign Fa0/5 to VLAN 10.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/6', why: 'First port of the HR group.' },
    { cmd: 'switchport mode access', why: 'Set access mode.' },
    { cmd: 'switchport access vlan 20', why: 'Assign Fa0/6 to VLAN 20 (HR).' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/7', why: 'Repeat for each HR port through Fa0/10.' },
    { cmd: 'switchport mode access', why: 'Set access mode.' },
    { cmd: 'switchport access vlan 20', why: 'Assign Fa0/7 to VLAN 20.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/8', why: 'Repeat for Fa0/8.' },
    { cmd: 'switchport mode access', why: 'Set access mode.' },
    { cmd: 'switchport access vlan 20', why: 'Assign Fa0/8 to VLAN 20.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/9', why: 'Repeat for Fa0/9.' },
    { cmd: 'switchport mode access', why: 'Set access mode.' },
    { cmd: 'switchport access vlan 20', why: 'Assign Fa0/9 to VLAN 20.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/10', why: 'Last HR port.' },
    { cmd: 'switchport mode access', why: 'Set access mode.' },
    { cmd: 'switchport access vlan 20', why: 'Assign Fa0/10 to VLAN 20.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface vlan 99', why: 'Create/enter the SVI for VLAN 99 to allow IP management.' },
    { cmd: 'ip address 192.168.99.1 255.255.255.0', why: 'Assign the management IP to the SVI.' },
    { cmd: 'no shutdown', why: 'Bring the SVI up — SVIs default to down.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'ip default-gateway 192.168.99.254', why: 'Set the gateway so the switch can reach remote networks.' },
    { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
    { cmd: 'copy running-config startup-config', why: 'Persist the configuration across reboots.' },
    { cmd: 'show vlan brief', why: 'Verify all three VLANs exist and ports are correctly assigned.' },
  ],
  validation: (state) => [
    { label: 'VLAN 10 (SALES) created', pass: !!state.vlans[10] && state.vlans[10].name === 'SALES' },
    { label: 'VLAN 20 (HR) created', pass: !!state.vlans[20] && state.vlans[20].name === 'HR' },
    { label: 'VLAN 99 (MGMT) created', pass: !!state.vlans[99] && state.vlans[99].name === 'MGMT' },
    { label: 'Fa0/1 assigned to VLAN 10', pass: state.interfaces['FastEthernet0/1']?.accessVlan === 10 },
    { label: 'Fa0/6 assigned to VLAN 20', pass: state.interfaces['FastEthernet0/6']?.accessVlan === 20 },
    { label: 'Vlan99 SVI has correct IP', pass: state.interfaces['Vlan99']?.ipAddress === '192.168.99.1' },
    { label: 'Default gateway set to 192.168.99.254', pass: state.defaultGateway === '192.168.99.254' },
    { label: 'Configuration saved', pass: !!state.startupConfig },
  ],
  initialState: createDefaultSwitchState(),
};