import { createDefaultSwitchState } from '../../switchState';

export default {
  id: 'test-office-vlan',
  title: 'Office VLAN Deployment',
  category: 'test',
  difficulty: 'Intermediate',
  duration: '25 min',
  description: 'A small office needs three VLANs: SALES (VLAN 10), HR (VLAN 20), and MGMT (VLAN 99). You must create the VLANs, assign ports, configure the management SVI with an IP address, and save the configuration.',
  objectives: [
    'Create VLAN 10 named SALES',
    'Create VLAN 20 named HR',
    'Create VLAN 99 named MGMT',
    'Assign Fa0/1–Fa0/5 to VLAN 10 (SALES)',
    'Assign Fa0/6–Fa0/10 to VLAN 20 (HR)',
    'Configure Vlan99 SVI with IP 192.168.99.1 255.255.255.0',
    'Set default gateway to 192.168.99.254',
    'Save the running configuration',
  ],
  hints: [
    'Create VLANs one at a time: "vlan 10" then "name SALES" inside vlan config mode',
    'To assign ports, enter each interface and use "switchport mode access" then "switchport access vlan 10"',
    'The SVI is configured with "interface vlan 99" then "ip address 192.168.99.1 255.255.255.0" and "no shutdown"',
    'Default gateway is set in global config: "ip default-gateway 192.168.99.254"',
    'Save with "copy running-config startup-config" or "write memory"',
  ],
  commands: [
    { cmd: 'vlan 10', why: 'Create VLAN 10 — enters VLAN config mode.' },
    { cmd: 'name SALES', why: 'Assign a human-readable name to VLAN 10.' },
    { cmd: 'vlan 20', why: 'Create VLAN 20.' },
    { cmd: 'name HR', why: 'Name VLAN 20.' },
    { cmd: 'vlan 99', why: 'Create management VLAN 99.' },
    { cmd: 'name MGMT', why: 'Name VLAN 99.' },
    { cmd: 'interface FastEthernet0/1', why: 'Enter interface config to assign to a VLAN.' },
    { cmd: 'switchport mode access', why: 'Force the port into access (not trunk) mode.' },
    { cmd: 'switchport access vlan 10', why: 'Assign the port to VLAN 10.' },
    { cmd: 'interface vlan 99', why: 'Create the SVI for VLAN 99 to allow IP management.' },
    { cmd: 'ip address 192.168.99.1 255.255.255.0', why: 'Assign the management IP to the SVI.' },
    { cmd: 'no shutdown', why: 'Bring the SVI up.' },
    { cmd: 'ip default-gateway 192.168.99.254', why: 'Set the gateway so the switch can reach remote networks.' },
    { cmd: 'copy running-config startup-config', why: 'Persist the configuration across reboots.' },
  ],
  validation: (state) => [
    { label: 'VLAN 10 (SALES) created', pass: !!state.vlans[10] && state.vlans[10].name === 'SALES' },
    { label: 'VLAN 20 (HR) created', pass: !!state.vlans[20] && state.vlans[20].name === 'HR' },
    { label: 'VLAN 99 (MGMT) created', pass: !!state.vlans[99] && state.vlans[99].name === 'MGMT' },
    { label: 'Fa0/1 assigned to VLAN 10', pass: state.interfaces['FastEthernet0/1']?.accessVlan === 10 },
    { label: 'Fa0/6 assigned to VLAN 20', pass: state.interfaces['FastEthernet0/6']?.accessVlan === 20 },
    { label: 'Vlan99 SVI has correct IP', pass: state.interfaces['Vlan99']?.ipAddress === '192.168.99.1' },
    { label: 'Default gateway set to 192.168.99.254', pass: state.defaultGateway === '192.168.99.254' },
    { label: 'Configuration saved', pass: !!state.startupConfig },
  ],
  initialState: createDefaultSwitchState(),
};