import { createDefaultSwitchState } from '../../switchState';

export default {
  id: 'test-secure-remote',
  title: 'Secure Remote Access Hardening',
  category: 'test',
  difficulty: 'Advanced',
  duration: '30 min',
  description: 'A security audit has flagged your switch for using Telnet and having no enable secret. You must harden the device: set a domain name, generate RSA keys, enable SSH v2, create an admin user, restrict VTY lines to SSH only, set an enable secret, and disable unused ports Fa0/13–Fa0/24.',
  objectives: [
    'Set domain name to corp.local',
    'Generate RSA keys (1024-bit)',
    'Enable SSH version 2',
    'Create user "admin" with password "Cisco123"',
    'Configure VTY lines to use SSH only (transport input ssh)',
    'Set VTY login to local',
    'Set enable secret to "Secure@123"',
    'Shutdown unused ports Fa0/13 through Fa0/24',
    'Save the configuration',
  ],
  hints: [
    'Domain name first — RSA key generation requires it: "ip domain-name corp.local"',
    'Generate keys: "crypto key generate rsa" — choose 1024 bit when prompted',
    'SSH version: "ip ssh version 2" in global config',
    'Create user: "username admin password Cisco123"',
    'VTY lines: "line vty 0 15" → "transport input ssh" → "login local"',
    'Enable secret: "enable secret Secure@123"',
    'Shutdown ports: enter each interface and run "shutdown"',
  ],
  commands: [
    { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
    { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
    { cmd: 'ip domain-name corp.local', why: 'Required before RSA key generation — forms part of the key identity.' },
    { cmd: 'crypto key generate rsa', why: 'Generates the RSA keypair that SSH uses to encrypt sessions. Enter 1024 when prompted for key size.' },
    { cmd: 'ip ssh version 2', why: 'Forces SSH v2 only — v1 has known vulnerabilities.' },
    { cmd: 'username admin password Cisco123', why: 'Creates a local user account for authentication.' },
    { cmd: 'enable secret Secure@123', why: 'Sets an encrypted enable password — more secure than "enable password".' },
    { cmd: 'line vty 0 15', why: 'Access all 16 virtual terminal lines at once.' },
    { cmd: 'transport input ssh', why: 'Allows ONLY SSH connections — Telnet is blocked.' },
    { cmd: 'login local', why: 'Use local usernames/passwords for VTY authentication.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/13', why: 'Target unused port Fa0/13 to disable it.' },
    { cmd: 'shutdown', why: 'Administratively disable Fa0/13 to prevent rogue device connections.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/14', why: 'Repeat for each unused port through Fa0/24.' },
    { cmd: 'shutdown', why: 'Disable Fa0/14.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/15', why: 'Disable Fa0/15.' },
    { cmd: 'shutdown', why: 'Disable Fa0/15.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/16', why: 'Disable Fa0/16.' },
    { cmd: 'shutdown', why: 'Disable Fa0/16.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/17', why: 'Disable Fa0/17.' },
    { cmd: 'shutdown', why: 'Disable Fa0/17.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/18', why: 'Disable Fa0/18.' },
    { cmd: 'shutdown', why: 'Disable Fa0/18.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/19', why: 'Disable Fa0/19.' },
    { cmd: 'shutdown', why: 'Disable Fa0/19.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/20', why: 'Disable Fa0/20.' },
    { cmd: 'shutdown', why: 'Disable Fa0/20.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/21', why: 'Disable Fa0/21.' },
    { cmd: 'shutdown', why: 'Disable Fa0/21.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/22', why: 'Disable Fa0/22.' },
    { cmd: 'shutdown', why: 'Disable Fa0/22.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/23', why: 'Disable Fa0/23.' },
    { cmd: 'shutdown', why: 'Disable Fa0/23.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/24', why: 'Last unused port to disable.' },
    { cmd: 'shutdown', why: 'Disable Fa0/24.' },
    { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
    { cmd: 'copy running-config startup-config', why: 'Save all security changes so they persist after a reboot.' },
    { cmd: 'show ip ssh', why: 'Confirm SSH v2 is enabled and running.' },
    { cmd: 'show running-config', why: 'Verify all settings: domain name, users, VTY config, enable secret, and shutdown interfaces.' },
  ],
  validation: (state) => [
    { label: 'Domain name set to corp.local', pass: state.domainName === 'corp.local' },
    { label: 'SSH version 2 enabled', pass: state.sshVersion === 2 },
    { label: 'Admin user created', pass: !!state.users?.admin },
    { label: 'VTY login set to local', pass: !!state.lines?.vty?.loginLocal },
    { label: 'VTY transport set to SSH', pass: state.lines?.vty?.transport === 'ssh' },
    { label: 'Enable secret configured', pass: !!state.enableSecret },
    { label: 'Fa0/13 shut down (unused port)', pass: state.interfaces['FastEthernet0/13']?.status === 'down' },
    { label: 'Configuration saved', pass: !!state.startupConfig },
  ],
  initialState: createDefaultSwitchState(),
};