import { createDefaultSwitchState } from '../../switchState';

export default {
  id: 'test-secure-remote',
  title: 'Secure Remote Access Hardening',
  category: 'test',
  difficulty: 'Advanced',
  duration: '30 min',
  description: 'A security audit has flagged your switch for using Telnet and having no enable secret. You must harden the device: set a domain name, generate RSA keys, enable SSH v2, create an admin user, restrict VTY lines to SSH only, set an enable secret, and disable unused ports Fa0/13–Fa0/24.',
  objectives: [
    'Set domain name to corp.local',
    'Generate RSA keys (1024-bit)',
    'Enable SSH version 2',
    'Create user "admin" with password "Cisco123"',
    'Configure VTY lines to use SSH only (transport input ssh)',
    'Set VTY login to local',
    'Set enable secret to "Secure@123"',
    'Shutdown unused ports Fa0/13 through Fa0/24',
    'Save the configuration',
  ],
  hints: [
    'Domain name first — RSA key generation requires it: "ip domain-name corp.local"',
    'Generate keys: "crypto key generate rsa" — choose 1024 bit when prompted',
    'SSH version: "ip ssh version 2" in global config',
    'Create user: "username admin password Cisco123"',
    'VTY lines: "line vty 0 15" → "transport input ssh" → "login local"',
    'Enable secret: "enable secret Secure@123"',
    'Shutdown ports: enter each interface and run "shutdown"',
  ],
  commands: [
    { cmd: 'ip domain-name corp.local', why: 'Required before RSA key generation.' },
    { cmd: 'crypto key generate rsa', why: 'Generates the RSA keypair that SSH uses to encrypt sessions.' },
    { cmd: 'ip ssh version 2', why: 'Forces SSH v2 only — v1 has known vulnerabilities.' },
    { cmd: 'username admin password Cisco123', why: 'Creates a local user account for authentication.' },
    { cmd: 'enable secret Secure@123', why: 'Sets an encrypted enable password — more secure than "enable password".' },
    { cmd: 'line vty 0 15', why: 'Access all 16 virtual terminal lines at once.' },
    { cmd: 'transport input ssh', why: 'Allows ONLY SSH connections — Telnet is blocked.' },
    { cmd: 'login local', why: 'Use local usernames/passwords for VTY authentication.' },
    { cmd: 'interface FastEthernet0/13', why: 'Target an unused port to disable it.' },
    { cmd: 'shutdown', why: 'Administratively disable the unused port to prevent rogue connections.' },
  ],
  validation: (state) => [
    { label: 'Domain name set to corp.local', pass: state.domainName === 'corp.local' },
    { label: 'SSH version 2 enabled', pass: state.sshVersion === 2 },
    { label: 'Admin user created', pass: !!state.users?.admin },
    { label: 'VTY login set to local', pass: !!state.lines?.vty?.loginLocal },
    { label: 'VTY transport set to SSH', pass: state.lines?.vty?.transport === 'ssh' },
    { label: 'Enable secret configured', pass: !!state.enableSecret },
    { label: 'Fa0/13 shut down (unused port)', pass: state.interfaces['FastEthernet0/13']?.status === 'down' },
    { label: 'Configuration saved', pass: !!state.startupConfig },
  ],
  initialState: createDefaultSwitchState(),
};