export default {
  id: 'ts-security-hardening',
  title: 'Security Hardening',
  category: 'troubleshooting',
  difficulty: 'Advanced',
  duration: '20 min',
  description: 'A security audit found several issues: no enable secret, unused ports are up, and CDP is enabled globally. Harden the switch configuration.',
  objectives: [
    'Set an enable secret password: "Str0ngPass!"',
    'Shut down all unused ports (Fa0/13 through Fa0/24)',
    'Disable CDP globally',
    'Save the hardened configuration',
  ],
  hints: [
    'Use "enable secret Str0ngPass!" in global config mode',
    'Enter each interface individually: "interface fa0/13" then "shutdown"',
    'Disable CDP with "no cdp run" in global config',
    'Save with "copy running-config startup-config"',
  ],
  commands: [
    { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
    { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
    { cmd: 'enable secret Str0ngPass!', why: 'Sets an MD5-encrypted enable password. Always prefer "enable secret" over "enable password" — the latter stores in reversible plaintext.' },
    { cmd: 'interface FastEthernet0/13', why: 'Target the first unused port. Best practice: shut down every port that has no device connected.' },
    { cmd: 'shutdown', why: 'Administratively disables Fa0/13. A shutdown port cannot be used by an attacker plugging in a rogue device.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/14', why: 'Shut down Fa0/14.' },
    { cmd: 'shutdown', why: 'Disable Fa0/14.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/15', why: 'Shut down Fa0/15.' },
    { cmd: 'shutdown', why: 'Disable Fa0/15.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/16', why: 'Shut down Fa0/16.' },
    { cmd: 'shutdown', why: 'Disable Fa0/16.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/17', why: 'Shut down Fa0/17.' },
    { cmd: 'shutdown', why: 'Disable Fa0/17.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/18', why: 'Shut down Fa0/18.' },
    { cmd: 'shutdown', why: 'Disable Fa0/18.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/19', why: 'Shut down Fa0/19.' },
    { cmd: 'shutdown', why: 'Disable Fa0/19.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/20', why: 'Shut down Fa0/20.' },
    { cmd: 'shutdown', why: 'Disable Fa0/20.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/21', why: 'Shut down Fa0/21.' },
    { cmd: 'shutdown', why: 'Disable Fa0/21.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/22', why: 'Shut down Fa0/22.' },
    { cmd: 'shutdown', why: 'Disable Fa0/22.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/23', why: 'Shut down Fa0/23.' },
    { cmd: 'shutdown', why: 'Disable Fa0/23.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/24', why: 'Shut down the last unused port, Fa0/24.' },
    { cmd: 'shutdown', why: 'Disable Fa0/24.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'no cdp run', why: 'CDP broadcasts device info (IOS version, model, IP) to neighbours. Disable it globally to prevent information disclosure on untrusted segments.' },
    { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
    { cmd: 'copy running-config startup-config', why: 'Persist the hardened config so all security settings survive a reboot.' },
    { cmd: 'show running-config', why: 'Verify the enable secret, shutdown interfaces, and "no cdp run" all appear correctly.' },
  ],
  validation: (state) => [
    { label: 'Enable secret is configured', pass: !!state.enableSecret },
    { label: 'Fa0/13 is shut down', pass: state.interfaces['FastEthernet0/13']?.status === 'down' },
    { label: 'Fa0/18 is shut down', pass: state.interfaces['FastEthernet0/18']?.status === 'down' },
    { label: 'Fa0/24 is shut down', pass: state.interfaces['FastEthernet0/24']?.status === 'down' },
    { label: 'CDP is disabled', pass: state.cdp === false },
    { label: 'Configuration saved', pass: !!state.startupConfig },
  ],
  initialState: null,
};