export default {
  id: 'ts-svi-no-ip',
  title: 'Management IP Not Reachable',
  category: 'troubleshooting',
  difficulty: 'Intermediate',
  duration: '15 min',
  description: "The network team can't SSH into the switch. The management VLAN interface (Vlan1) has no IP address configured. Set up remote management access.",
  objectives: [
    'Use "show ip interface brief" to see Vlan1 has no IP',
    'Assign IP address 192.168.1.10/24 to Vlan1',
    'Configure a default gateway of 192.168.1.1',
    'Set up VTY password "cisco123" and enable login',
    'Verify with "show running-config"',
  ],
  hints: [
    '"show ip interface brief" shows Vlan1 with "unassigned" for its IP',
    'Enter "interface vlan 1" then "ip address 192.168.1.10 255.255.255.0"',
    'Set the gateway in global config: "ip default-gateway 192.168.1.1"',
    'Configure VTY: "line vty 0 4" → "password cisco123" → "login"',
  ],
  commands: [
    { cmd: 'show ip interface brief', why: 'Confirms Vlan1 has "unassigned" IP — no IP means no remote management is possible.' },
    { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
    { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
    { cmd: 'interface vlan 1', why: 'The SVI (Switch Virtual Interface) for VLAN 1 is the management interface.' },
    { cmd: 'ip address 192.168.1.10 255.255.255.0', why: 'Assigns the management IP. Remote users SSH/Telnet to this address to reach the switch.' },
    { cmd: 'no shutdown', why: 'SVIs can be administratively down — always ensure the management interface is enabled.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'ip default-gateway 192.168.1.1', why: "Without a default gateway, the switch can't route reply packets back to hosts on other subnets." },
    { cmd: 'line vty 0 4', why: 'Configures the virtual terminal lines (0 through 4) for SSH/Telnet remote access.' },
    { cmd: 'password cisco123', why: 'Sets the VTY password required for remote login.' },
    { cmd: 'login', why: 'Enables password checking on the VTY lines. Without this, no password is required.' },
    { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
    { cmd: 'show running-config', why: 'Verify the Vlan1 IP, default gateway, and VTY configuration all appear correctly.' },
  ],
  validation: (state) => [
    { label: 'Vlan1 has an IP address', pass: state.interfaces['Vlan1']?.ipAddress && state.interfaces['Vlan1']?.ipAddress !== 'unassigned' },
    { label: 'Default gateway is set', pass: !!state.defaultGateway },
    { label: 'VTY password is configured', pass: !!state.lines?.vty?.password },
    { label: 'VTY login is enabled', pass: !!state.lines?.vty?.login },
  ],
  initialState: null,
};