export default {
  id: 'interface-management',
  title: 'Interface Management',
  difficulty: 'Beginner',
  duration: '10 min',
  description: 'Practice enabling, disabling, and configuring switch interfaces.',
  objectives: [
    'Shut down interfaces Fa0/20 through Fa0/24 (unused ports)',
    'Add a description to Fa0/1: "Server Room Link"',
    'Set Gi0/1 description to "Uplink to Router"',
    'Verify with "show ip interface brief"',
  ],
  commands: [
    { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
    { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/20', why: 'Target the first unused port to shut down.' },
    { cmd: 'shutdown', why: 'Administratively disables the port. Best practice: always shut down unused ports to prevent unauthorized access.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/21', why: 'Target the next unused port.' },
    { cmd: 'shutdown', why: 'Shut down Fa0/21.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/22', why: 'Target Fa0/22.' },
    { cmd: 'shutdown', why: 'Shut down Fa0/22.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/23', why: 'Target Fa0/23.' },
    { cmd: 'shutdown', why: 'Shut down Fa0/23.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/24', why: 'Target the last unused port.' },
    { cmd: 'shutdown', why: 'Shut down Fa0/24.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/1', why: 'Move to the port connected to the server room.' },
    { cmd: 'description Server Room Link', why: 'Labels this port in the config and show commands. Essential for troubleshooting in a real network.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface GigabitEthernet0/1', why: 'Move to the uplink port to add its description.' },
    { cmd: 'description Uplink to Router', why: 'Documents the uplink port for future reference.' },
    { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
    { cmd: 'show ip interface brief', why: 'Compact table showing every interface and its up/down status. Confirms shutdowns took effect.' },
  ],
  validation: (state) => [
    { label: 'Fa0/20 is shutdown', pass: state.interfaces['FastEthernet0/20']?.status === 'down' },
    { label: 'Fa0/24 is shutdown', pass: state.interfaces['FastEthernet0/24']?.status === 'down' },
    { label: 'Fa0/1 has description', pass: state.interfaces['FastEthernet0/1']?.description === 'Server Room Link' },
    { label: 'Gi0/1 has description', pass: state.interfaces['GigabitEthernet0/1']?.description === 'Uplink to Router' },
  ],
  initialState: null,
};