export default {
  id: 'port-security',
  title: 'Port Security',
  difficulty: 'Intermediate',
  duration: '15 min',
  description: 'Protect the network by limiting which MAC addresses can connect to specific switch ports. Configure port security on Fa0/1 and Fa0/2 with sticky MAC learning and shutdown violation mode.',
  objectives: [
    'Enable port security on Fa0/1',
    'Set maximum MAC addresses to 1 on Fa0/1',
    'Enable sticky MAC learning on Fa0/1',
    'Set violation mode to "shutdown" on Fa0/1',
    'Repeat port security configuration on Fa0/2',
  ],
  hints: [
    'Port must be in access mode before enabling port security',
    'Use "switchport port-security" to enable it',
    'Use "switchport port-security maximum 1" to allow only one device',
    'Use "switchport port-security mac-address sticky" for dynamic learning',
    'Use "switchport port-security violation shutdown" to shut down on violation',
  ],
  commands: [
    { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
    { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/1', why: 'Target the first port to secure.' },
    { cmd: 'switchport mode access', why: 'Port security only works on access ports — the port must not be in dynamic or trunk mode.' },
    { cmd: 'switchport port-security', why: 'Enables port security on this interface. No restrictions apply until you add more commands.' },
    { cmd: 'switchport port-security maximum 1', why: 'Limits the port to one MAC address. If a second device connects, the violation action triggers.' },
    { cmd: 'switchport port-security mac-address sticky', why: 'Dynamically learns the first MAC address and saves it to the config — no need to manually specify MAC addresses.' },
    { cmd: 'switchport port-security violation shutdown', why: 'The most strict violation mode — the port is err-disabled if an unauthorized MAC is detected. Use "no shutdown" to recover.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/2', why: 'Apply the same port security policy to Fa0/2.' },
    { cmd: 'switchport mode access', why: 'Ensure Fa0/2 is in access mode.' },
    { cmd: 'switchport port-security', why: 'Enable port security on Fa0/2.' },
    { cmd: 'switchport port-security maximum 1', why: 'Allow only one MAC address on Fa0/2.' },
    { cmd: 'switchport port-security mac-address sticky', why: 'Enable sticky learning on Fa0/2.' },
    { cmd: 'switchport port-security violation shutdown', why: 'Set shutdown as the violation action on Fa0/2.' },
    { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
    { cmd: 'show running-config', why: 'Verify port security settings appear on both Fa0/1 and Fa0/2.' },
  ],
  validation: (state) => [
    { label: 'Port security enabled on Fa0/1', pass: !!state.interfaces['FastEthernet0/1']?.portSecurityEnabled },
    { label: 'Fa0/1 maximum set to 1', pass: state.interfaces['FastEthernet0/1']?.portSecurityMaximum === 1 },
    { label: 'Fa0/1 sticky MAC learning enabled', pass: !!state.interfaces['FastEthernet0/1']?.portSecuritySticky },
    { label: 'Fa0/1 violation mode is shutdown', pass: state.interfaces['FastEthernet0/1']?.portSecurityViolation === 'shutdown' },
    { label: 'Port security enabled on Fa0/2', pass: !!state.interfaces['FastEthernet0/2']?.portSecurityEnabled },
  ],
  initialState: null,
};