export default {
  id: 'spanning-tree',
  title: 'Spanning Tree Protocol',
  difficulty: 'Intermediate',
  duration: '15 min',
  description: 'Configure Rapid PVST+, set bridge priority to make this switch the STP root for VLAN 10, and enable PortFast with BPDU Guard on access ports to speed up host convergence.',
  objectives: [
    'Change spanning-tree mode to "rapid-pvst"',
    'Create VLAN 10 named "DATA"',
    'Set STP root for VLAN 10 using bridge priority 4096',
    'Enable PortFast on Fa0/1',
    'Enable BPDU Guard on Fa0/1',
  ],
  commands: [
    { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
    { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
    { cmd: 'spanning-tree mode rapid-pvst', why: 'Rapid PVST+ converges much faster than classic PVST (seconds vs 30-50 seconds). Always use rapid-pvst in modern networks.' },
    { cmd: 'vlan 10', why: 'Create VLAN 10 — you must have the VLAN before configuring STP parameters for it.' },
    { cmd: 'name DATA', why: 'Name VLAN 10 for documentation.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'spanning-tree vlan 10 priority 4096', why: 'Sets the bridge priority for VLAN 10. Lower priority = preferred root. 4096 ensures this switch wins the root election for VLAN 10.' },
    { cmd: 'interface FastEthernet0/1', why: 'Enter the access port where hosts connect.' },
    { cmd: 'spanning-tree portfast', why: 'Skips the STP listening and learning states (normally 30 seconds total). Hosts get network access instantly. Only use on ports connected to end devices — NEVER on trunk ports.' },
    { cmd: 'spanning-tree bpduguard enable', why: 'Disables the port immediately if a BPDU is received — protects against someone plugging a rogue switch into this access port.' },
    { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
    { cmd: 'show spanning-tree', why: 'Verify this switch is the root bridge for VLAN 10 and the mode shows rapid-pvst.' },
    { cmd: 'show spanning-tree summary', why: 'Shows a high-level summary of STP mode and PortFast/BPDU Guard defaults.' },
  ],
  validation: (state) => [
    { label: 'Spanning-tree mode set to rapid-pvst', pass: state.spanningTreeMode === 'rapid-pvst' },
    { label: 'VLAN 10 exists with name "DATA"', pass: state.vlans[10]?.name === 'DATA' },
    { label: 'Fa0/1 PortFast enabled', pass: !!state.interfaces['FastEthernet0/1']?.spanningTreePortfast },
    { label: 'Fa0/1 BPDU Guard enabled', pass: !!state.interfaces['FastEthernet0/1']?.spanningTreeBpduguard },
  ],
  initialState: null,
};