export default {
  id: 'ssh-setup',
  title: 'SSH Remote Access Setup',
  difficulty: 'Intermediate',
  duration: '15 min',
  description: 'Configure secure remote management access via SSH. You will set a domain name, generate RSA keys, create a local user, and restrict VTY lines to SSH only.',
  objectives: [
    'Set the domain name to "lab.local"',
    'Generate RSA crypto keys (modulus 1024)',
    'Create local user "admin" with password "cisco123"',
    'Configure VTY lines to use local login and SSH only',
    'Verify with "show ip ssh"',
  ],
  commands: [
    { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
    { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
    { cmd: 'ip domain-name lab.local', why: 'A domain name is required before RSA keys can be generated — it forms part of the key name (hostname.domain).' },
    { cmd: 'crypto key generate rsa', why: 'Generates the RSA key pair needed by SSH. Without keys, the SSH server cannot start.' },
    { cmd: 'username admin password cisco123', why: 'Creates a local user account. SSH with local login requires at least one username/password pair in the local database.' },
    { cmd: 'ip ssh version 2', why: 'Forces SSH version 2, which is more secure than version 1. Always specify v2 in production.' },
    { cmd: 'line vty 0 4', why: 'Enters configuration mode for the 5 virtual terminal lines used for remote sessions.' },
    { cmd: 'login local', why: 'Tells the VTY lines to authenticate using the local user database (the username/password you just created).' },
    { cmd: 'transport input ssh', why: 'Restricts remote access to SSH only — Telnet is blocked. This is a critical security setting.' },
    { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
    { cmd: 'show ip ssh', why: 'Confirms SSH is enabled, shows the version, and displays timeout/retry settings.' },
    { cmd: 'show running-config', why: 'Verify domain name, username, and VTY configuration all appear in the config.' },
  ],
  validation: (state) => [
    { label: 'Domain name is set', pass: !!state.domainName },
    { label: 'SSH version 2 configured', pass: state.sshVersion === 2 },
    { label: 'Local user "admin" created', pass: !!state.users?.admin },
    { label: 'VTY login local configured', pass: !!state.lines?.vty?.loginLocal },
    { label: 'VTY transport restricted to SSH', pass: state.lines?.vty?.transport === 'ssh' },
  ],
  initialState: null,
};