export default {
  id: 'trunk-config',
  title: 'Trunk Port Configuration',
  difficulty: 'Intermediate',
  duration: '10 min',
  description: 'Configure trunk ports on the GigabitEthernet uplinks for inter-switch VLAN traffic.',
  objectives: [
    'Create VLAN 10 (SALES) and VLAN 20 (ENGINEERING)',
    'Configure GigabitEthernet0/1 as a trunk port',
    'Configure GigabitEthernet0/2 as a trunk port',
    'Add descriptions to both trunk interfaces',
    'Verify with "show interfaces trunk"',
  ],
  hints: [
    'First create the VLANs in config mode',
    'Enter interface config: "interface gi0/1"',
    'Set trunk mode: "switchport mode trunk"',
    'Add description: "description Uplink to Core Switch"',
    'Repeat for Gi0/2, then verify with "show interfaces trunk"',
  ],
  commands: [
    { cmd: 'enable', why: 'Enter Privileged EXEC mode.' },
    { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
    { cmd: 'vlan 10', why: 'Create VLAN 10 — trunk ports carry all VLANs, so they must exist first.' },
    { cmd: 'name SALES', why: 'Name VLAN 10 for clarity.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'vlan 20', why: 'Create VLAN 20.' },
    { cmd: 'name ENGINEERING', why: 'Name VLAN 20.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface GigabitEthernet0/1', why: 'GigabitEthernet ports are typically used for uplinks because of their higher bandwidth.' },
    { cmd: 'switchport mode trunk', why: 'A trunk port carries traffic for multiple VLANs simultaneously using 802.1Q tagging.' },
    { cmd: 'description Uplink to Core Switch', why: 'Always document trunk ports so future admins know what is connected.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode to configure the second uplink.' },
    { cmd: 'interface GigabitEthernet0/2', why: 'Enter the second uplink interface.' },
    { cmd: 'switchport mode trunk', why: 'Configure Gi0/2 as a trunk port as well.' },
    { cmd: 'description Uplink to Distribution Switch', why: 'Document the second trunk link.' },
    { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
    { cmd: 'show interfaces trunk', why: 'Verifies both Gi0/1 and Gi0/2 are in trunking mode and shows allowed VLANs.' },
  ],
  validation: (state) => [
    { label: 'VLAN 10 exists', pass: !!state.vlans[10] },
    { label: 'VLAN 20 exists', pass: !!state.vlans[20] },
    { label: 'Gi0/1 is trunk', pass: state.interfaces['GigabitEthernet0/1']?.switchportMode === 'trunk' },
    { label: 'Gi0/2 is trunk', pass: state.interfaces['GigabitEthernet0/2']?.switchportMode === 'trunk' },
    { label: 'Gi0/1 has description', pass: !!state.interfaces['GigabitEthernet0/1']?.description },
    { label: 'Gi0/2 has description', pass: !!state.interfaces['GigabitEthernet0/2']?.description },
  ],
  initialState: null,
};