export default {
  id: 'vlan-config',
  title: 'VLAN Configuration',
  difficulty: 'Intermediate',
  duration: '15 min',
  description: 'Create VLANs and assign ports to different VLANs for network segmentation.',
  objectives: [
    'Create VLAN 10 and name it "SALES"',
    'Create VLAN 20 and name it "ENGINEERING"',
    'Assign FastEthernet0/1 through Fa0/6 to VLAN 10',
    'Assign FastEthernet0/7 through Fa0/12 to VLAN 20',
    'Verify with "show vlan brief"',
  ],
  commands: [
    { cmd: 'enable', why: 'Enter Privileged EXEC mode before making changes.' },
    { cmd: 'configure terminal', why: 'Enter Global Configuration mode.' },
    { cmd: 'vlan 10', why: 'Creates VLAN 10 and enters VLAN config mode. VLANs segment a switch into isolated broadcast domains.' },
    { cmd: 'name SALES', why: 'Assigns a human-readable name to VLAN 10 so it is identifiable in show commands.' },
    { cmd: 'exit', why: 'Returns from VLAN config mode back to Global Configuration mode.' },
    { cmd: 'vlan 20', why: 'Creates VLAN 20 for the Engineering team.' },
    { cmd: 'name ENGINEERING', why: 'Names VLAN 20 for clarity.' },
    { cmd: 'exit', why: 'Returns to Global Configuration mode. Both VLANs must exist before assigning ports to them.' },
    { cmd: 'interface FastEthernet0/1', why: 'Enter interface config for Fa0/1. Ports are assigned one at a time.' },
    { cmd: 'switchport mode access', why: 'Explicitly sets the port to access mode — a port that belongs to exactly one VLAN.' },
    { cmd: 'switchport access vlan 10', why: 'Assigns Fa0/1 to VLAN 10 (SALES). The VLAN must already exist or this command will fail.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode to configure the next port.' },
    { cmd: 'interface FastEthernet0/2', why: 'Repeat for Fa0/2 — you must configure each port individually (no range support in this simulator).' },
    { cmd: 'switchport mode access', why: 'Set Fa0/2 to access mode.' },
    { cmd: 'switchport access vlan 10', why: 'Assign Fa0/2 to VLAN 10.' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/7', why: 'Enter interface config for Fa0/7 — first port of the ENGINEERING group.' },
    { cmd: 'switchport mode access', why: 'Set Fa0/7 to access mode.' },
    { cmd: 'switchport access vlan 20', why: 'Assigns Fa0/7 to VLAN 20 (ENGINEERING).' },
    { cmd: 'exit', why: 'Return to Global Configuration mode.' },
    { cmd: 'interface FastEthernet0/8', why: 'Continue assigning ENGINEERING ports. Repeat this pattern through Fa0/12.' },
    { cmd: 'switchport mode access', why: 'Set Fa0/8 to access mode.' },
    { cmd: 'switchport access vlan 20', why: 'Assign Fa0/8 to VLAN 20.' },
    { cmd: 'end', why: 'Return to Privileged EXEC mode.' },
    { cmd: 'show vlan brief', why: 'Confirms which ports belong to which VLANs. Fa0/1-6 should appear under VLAN 10, Fa0/7-12 under VLAN 20.' },
  ],
  validation: (state) => [
    { label: 'VLAN 10 exists with name "SALES"', pass: state.vlans[10]?.name === 'SALES' },
    { label: 'VLAN 20 exists with name "ENGINEERING"', pass: state.vlans[20]?.name === 'ENGINEERING' },
    { label: 'Fa0/1 assigned to VLAN 10', pass: state.interfaces['FastEthernet0/1']?.accessVlan === 10 },
    { label: 'Fa0/7 assigned to VLAN 20', pass: state.interfaces['FastEthernet0/7']?.accessVlan === 20 },
  ],
  initialState: null,
};